---
title: ''
author: "David John Baker"
date: "DATE"
output: pdf_document
classoption: twoside
header-includes:
   - \usepackage[none]{hyphenat}
fontsize: 12pt
geometry: "left=4cm, right=3cm, top=2.5cm, bottom=2.5cm"
---

\pagenumbering{gobble}

# Abstract 


Melodic dictation is a cognitively demanding process that requires students to hear a melody, then without any access to an external reference, transcribe the melody within a limited time frame. 
Despite its ubiquity in curricula within School of Music settings, exactly how an individual learns a melody is not well understood. 
This dissertation aims to fill the gap in the literature between aural skills practitioners and music psychologists in order to reach conclusions that can be applied systematically in pedagogical contexts. 
I accomplish this by synthesizing literature from music theory, music psychology, and music education in order to demonstrate how tools from both cognitive psychology as well as computational musicology can be used to help inform pedagogical practices.

In the first chapter, I discuss factors that  might play a role in a student's ability to take melodic dictation and put forward a taxonomy of factors that are assumed to contribute to an individual’s ability to take melodic dictation. 
The second chapter of the dissertation investigates individual factors that are theorized to contribute to melodic dictation using a cross-sectional experimental design. 
The chapter corroborates claims on the importance of understanding individual differences in working memory capacity in research on melodic dictation. 
The third chapter discusses how aural skills pedagogy can incorporate methodologies from computational musicology in order to inform teaching practice. 
In my fourth chapter, I introduce the MeloSol corpus, a new collection of 783 digitized melodies encoded in the **kern format. 
In the fifth chapter, I synthesize the previous research in a melodic dictation experiment to show how using robust statistical methods can be used model melodic dictation. 
Finally, in my sixth chapter, I introduce a computational, cognitive model of melodic dictation with the goal of helping explain how students improve at melodic dictation. 
I demonstrate how modeling the cognitive decision process during melodic dictation helps provide a precise framework for pedagogues to understand student’s inner cognition during melodic dictation and can help inform teaching practice. 
