---
title: ''
author: "David John Baker"
date: "DATE"
output: pdf_document
classoption: twoside
header-includes:
   - \usepackage[none]{hyphenat}
fontsize: 12pt
geometry: "left=1.5in, right=1in, top=2.5in, bottom=2.5in"
---
\pagenumbering{gobble}
© 2019 copyright 

David John Baker 

All rights reserved 

\newpage

This dissertation is dedicated to my parents-- John and Mary Baker--who instilled love support in education. 


\newpage 

This dissertation would not have been possible without the support of a large community people over the past four years.
First and foremost, I would like to acknowledge and thank my dissertation committee. 
Daniel Shanahan, my main supervisor throughout my PhD, who provided me with countless office conversations, cups of coffee at Highland, and allowed me the freedom to pursue my interests while a student; Emily Elliott for unmatched support and guidance; .
Robert Peck for constant reminder and inspiration that music and math go together. 

Secondly, the entire Louisiana State University community for always making me feel welcomed and supported and existed as a constant source of knowledge throughout my time as a student.
This includes the Music Cognition and Computation Lab at LSU, the weekly Tin Roof Trivia group, and all the professors who gave me oppertunities that I never imagined having including Jason Harman.

Thirdly, I want to especially thank those who either went out of their way to help me learning the more technical side of research who often go unaknowledged.
Craig Sapp for feature requests in Humdrum, Xie for writing bookdown, and the #rstats community, specifally Hadely Wickahm, X Y for everything with the tidyverse.
Without committment to open and accessible software, this dissertation would not have been possible.

Fourth, want to thank for all the social support groups floated around during PhD.
Everyone I have met through the Music, Mind and Brain group in London.
Particularly Daniel Müllensiefen and Peter Harrison for software and sounding board for ideas, also Marus Pearce for inviting me to be part of QM group while in London writing up. 

Fifth, want to thank everyone I have known from Ohio.
Without getting telological, don't know if I would have ended up on this path without support of professors who listened to what I wanted to do, specifically Christine Dorey for suggesting I email David Huron, who in a 90 minute phone call that night carved out a career plan that I happened to follow. 

I also want to thank that #musicsciecne community on Twitter for being there.

Evelyn Stanley for support, listening, and listening to my tub talks.

Lastly, thank family who I am very lucky to have.
Lucky to happen to have been born with people who not only support and value education, but also support and value ...
