# Theoretical Background and Rationale {#intro}

## What is melodic dictation? and Why?

Melodic dictation is the process in which an individual hears a melody, retains it in memory, and then uses their knowledge of Western musical notation to recreate the mental image of it on paper in a limited time frame.
For many, becoming profiecent at this task is at the core of developing one's aural skills [@karpinskiModelMusicPerception1990].
For over a century, music pedagoges have highly valued melodic dictation^[In his highly influenctial book _Aural Skills Acquisition: The Development of Listening, Reading, and Performing Skills in College-Level Musicians_, Gary @karpinskiAuralSkillsAcquisition2000 documents this deeply held belief in music pedagogy circles by listing poetic adages from romantic composer Robert Schumann in the mid 19th century through music educator Charles Elliott in the opening of his book,  providing concrete examples of the belief that improving one's aural skills, or _ear_, is a highly sought after advanced skill. ] and most aural skills texts that have sections devoted to honing one's listening skills have material on melodic dictation [@karpinskiAuralSkillsAcquisition2000].
Additionally, any school acredited by the North American Schools of Music requires learning this skill be part of any acredited curriula.
Yet despite this tradition and ubiquity, the rationales as to _why_ it is important for students to learn this ability often comes from some sort of appeal to tradition or underwhelming anecdotal evidence that time spent learning to take melodic dictation results in increases in near transfer abilities after they have acquired a certain degree of profieency. 
Rationales given for why students should learn melodic dictation has even been described by Gary Karpinski as being based on "compratively vauge aphorisms about mental relationships and intelligent listenings" [@karpinskiModelMusicPerception1990, p.192], with the argument for learning to take melodic dictation historically not being well supported with persuasive evidence. 

Some researchers have even taken a more skeptical stance and have noted that the rationale for why we teach melodic dictation  deserves more critique.
For example, Klonoski in writing about aural skills education aptly questions "What specific deficiency is revelaned with an incorrect reponse in melodic dictaiton settings?" [@klonoskiImprovingDictationAuralSkills2006].
Earlier researchers like Potter, in their own publication, have noted that they have been baffled that many musicians do not actually keep up with their melodic dictation abilities after the classs ends [@potterIdentifyingSucessfulDictation1990], but presumably go on to have sucessful and fulfilling musical lives. 
Additionally, suggesting that people who can hear music and then are unable to write it down, and thus are unable to think _in_ music, seems somewhat exclusionary to the vast amount of musical cultures out there that do not depend on any sort of written notation. 

Though despite this skepticism towards the topic, melodic dictation remains at the forefront of many aural skills classrooms.
While the act of becoming better at this skill may or may not lead to large in increases in far transfer of ability, as a pedagogical tool, teaching students to take melodic dictation brings with it the concepts that are hoped to be instilled in music students long term.
While not there has not been extensive research on melodic dictation research in the past few years, in fact [@paneyEffectDirectingAttention2016] notes that since 2000, only four studies were published that directly examined melodic dictation, this skill set sits on the border between literature on learning, melodic perception, memory, and music theory pedagogy and understanding and modeling exactly how it works remains as a untapped watershed of knowledge for the field of music theory, music education, and music perception and is deserving of much more attention. 


### Describing Melodic Dictation 

Much of the foundational work on the topic of melodic dictation comes from the work of Gary Karpinski.
Summerized most recently in his _Aural Skills Acquisition_ [@karpinskiAuralSkillsAcquisition2000], though first presented in an earlier article [@karpinskiModelMusicPerception1990], Karpinski proposes his own model of melodic dictation that provides a four step framework as how the process of melodic dictation works.^[In Karpinski 1990 he notes two other models of melodic dictation, one from Rogers where he says there are 2 processes, another from Thomas who says there are 15] 

His four steps include:

1. Hearing
2. Short Term Melodic Memory
3. Musical Understanding 
4. Notation

and occur as a looping, schematic process that is depicted in Figure 3.1 in his textbook, reproduced below and htroughout the chapter Karpinski discusses relevant factors at play at each stage.
In the case of the table above, the process happens twice, presumably with a melody that can be extracted in two parts, which according to Karpinski and this prescribed formulas would consist of a melody from twelve to twent notes long for listenrs with few or no chunking abilities. 
Reviewing the Karpinksi four step model will provide both a grounding in the current model that has been used in other litearture, and establish a groundwork from which to build. 

The **hearing** stage involves the initial peceptions of the sound at a physical level of the tympanic membrane, as well as the listener's _attention_ to the incoming musical information.
If the listener is not actively engaging in the task because of factors like "bordeom, lack of discipline, test anxiety, attention defict disorder, or any number of other causes" then any futher processes down the model will be determentially effected. 
While Karpinski nots that these types of interference are normally "beyond the traditional juristiction of aural skills instruction", I will later argue that the concept of willfull attention when reconceptualized as working memory capacity, may actually play a large role in the melodic dictation process. 

The **short-term melodic memory** Karpinski relies on empirical qualitative evidence from interview with students to show support for two separate memory encoding mechanisms, one for contour, and one for pitch.
After citing literature supporting this claim (DOWLING 1978, DeWITT AND CROWDWER 1986, DOWLING 1994) regarding contour, as well as litertuare suggesting that in order to memorize chunks of melodic material, it helps to have been enculturated (DEUTSCH 1977,Oura and Hatano 1988, Handel 1989, Davies 1978, Dowling 1990) (a field of research that has been explored a lot since this was published PEARCE WORK), Karpinksi explains how ideas like extractive listening and chunking then take part in this process.
Noting that there is probably some sort of capacity limit to music, citing Miller (1956) and corroborating musical evidence (Marple n.d)^[Should probalby do some foot note here saying this is wrong use of miller for reasons in Cowan 2005 and Miller is even on record as saying the magic number 7 was just used to thread his speech together...], Karpinski details the two stragegies from above to show how the dictation process is done.
Karpinski's extractive listening refers to only selectively remembering parts of a melody.
The chunking bit isa an idea that as musical understanding increases, so does musical memory.
The idea is that if you can identify certain ideas that you hear in the incoming signal, you can more effectively undertand them. 

In order to further explain the idea of **musical understanding** Karpinski says its different ha musical memory. 
Musical memory for Karpinski is ability to repeat what has been heard, and understanding is about comprehending things like the hierarchical metrical relationships between notes, rhythmic groupings and tonal functions.
Within this whole idea is the thing of solimization for both rhythm and pitch (the takdimiti system KODALY) and relative pitch.
Idea here is that hte two are then going to be linked to one another and as information comes in that can be musically understood, then it can then be moved from perception to notation more quickly.

The **notation**, and final step of the dictation loop, require the knowledge of Western musical notation to be able to write down what is in one's musical short term memory and use their musical understanding to decode that mental representation into written notation. 
This last step is ripe for errors as Karpinski notes has been foudn in other areas of research TAYLOR AND PEMBROOK 1983 and its noted that obviously it's very hard to write something down if you don't have the category for it. 

The final parts of the chapter, Karpinski notes that other factors like **tempo**, the **length** and **number of playings**, and the **duration between playings** will also play a role in determining how an individual will perform on a melodic dictation.
While this framework can help illuminate this cognitive process and help pedagogues understand how to best help their students, the model as it stands is not detialed enough for explanatory purposes and does not exhaust the many factors that further research since its publicaiton have demonstrated as relevant making a model of melodic dictation.



Again, though Karpinski did not intent to create an exhaustive model of the melodic dictaiton process, by only creating a verbal model, the model is unprepared to handle a few basic things which are just the next logical research step.



From this point on, need tone to suggest that what Karpinski did is good, but the next step is to get more formal with it and be able to start investigating factors that go into doing melodic dictation.
Would be good to know how the process works and in order to do that need to look at it as it happens with experimental approaches, and additionally want to try to make a model of it to make sure we include everything.

Title of dissertatino is modeling melodic dictation, want to have model that describes it and its component parts, and want to have a model that describes the process. 

have argument

HERE IS WHERE YOU TALK ABOUT WHY THERE IS A NEED FOR A COMPUTATIONAL MODEL AND EXPERIMENTAL MODEL

Primarily, having a single model for melodic dictation assumes that all individuals are likely to engage in this sequential ordering of events.
This could in fact be the case, but there is research ANDREW GOLDMAN AND STUFF that suggests that experts process and categorize musical information differently. 
Additionally, different people will probably have different experiences dictating melodies based on their own past listening experience, a note that Karpinski makes earlier when THAT CITATION FROM UP ABOVE. 
Not only will there be differences in ability, additionally people differ in their cognitive abilities.
The model does not have any flexibility in terms of individual differences.

Secondly, the model also does not seem to treat melodies differently.
For example, on page 103, Karpinski suggest that two passes should be adequate for a listern with few to no chunking skills to listen to be able to dictate a melody of twelve to twenty notes.
This also would be an area of model improvement, as both the melodies listed below here are XX notes, within Karpinski's prescribed range, but intuition might suggest that the melodies are not equally difficult to dictate.
The model is agnostic towards differences in melodies.

In order to have a model that will eventually be able to incorporate everything involved in the melodic dictaiton process, and to be eventually implemented computationally, it is nesseacry to createa new taxonomy of factors that could contribute to modeling melodic dictation.
In the 18 years since the publication of _Aural Skills Acquisition_, there has been a wealth of research that has been done on factors related to melodic dictation.
I am convinced that the best way to taxonomize the multitude of factors contributing to this is to create a taxonomy where musical and individual factors are at the highest.


#### Individual Factors to contribute 

From an individual stand point, can bifurcate factors broadly into *cognitive factors*, or factors of people that are relatively consistent over people or basically like fixed effects things (use definiton of what is a fixed effect); and the other side of this would be things that would have to be delt with that change with training and exposure. 
Going to refer to this second set of things as *environmental* factors. 
Is there a better way to talk about this as nature vs nurture.
Addiitonally need to then mention that there are of course epigenitic factors where both of these parameters might interact with one another. 
For example, might then imagine that someone with higher cognitive abilitty, lots of training that was put forward by their parents, as well as tons of musical training, and personality traits that are more likely to learn more (daniels paper on that) might be different in terms of resutls than someone with lower cognitive abilities, no training, low SES, and a general inclination not to even take music lessons. 
While obvious, what will eventually be of interest is the degree to which each of these things contributes to the final models.
Also gives us a better idea about pedagogy and what not. 

#### Musical factors to contribute

In addition to differences at the individual level, there are also musical level characteristics.
In this category it is also worth taxonimizing the musical characterstics into two categories as well.
On one hand we have the structural aspects of the melody itself.
These are aspects of the melody that would remain invariant when written down on a score.
Reading from left to right, would be things like range, key, time signature, intervals, amount of notes, contour of the melody, tonal properties, standardized note density.
Then the other side would be musical features that I am going to deem as experiemntal features of the melody.
These are aspects of the structure of hte melody that you can then warp within the context of a melodic dictiation such as tempo, which then refelcts note density, timbral qualities, how many times the melody is played, the space between hearings. 
This is not a categorial divide, while I put something like range as key of the melody as structural, you could imagine that you could have hte same interval invariant structure of a melody , perhaps Twinkle, Twinkle little star begginging on C2 noteated in bass cleff, but then imagine the the same "melody" being played two and a half octaves up on F#4, and transposed to minor and played quicker leading ot a phenomenologically similar experience, but not the same.
I taxonimze them early on, but again note that a model of this should be able withstand the multitude of patterns that exist. 

#### Make a Model of them 

Given all of these factors that then go into the melodic dictaiton process, the remainder of this chapter will detail previous reserach that has gone into each of these factors.
Talking about each one will provide rationale for why it should be further investigated if we are to better understand melodic dictation.
Beginning with *cognitive factors* two levels, then go on to talk about *musical features*.
After discussing both and their two subcompoents as I have taxonimzed them, offer a brief discussion on how it's bad to think about these as just latent abilities.
Instead talk about thinking about modeling melodic dictaiton, in terms of ACTUAL MODELING, as polymorphic conceptualization of aural skills. 
This is important because how we talk about and model things reflects or values and often it will get in the way of stuff. 

This is important because the end goal of this research is to be able to model this from an experimental and comptuational level. 

From an empirical standpoint, both the task as well as the process of melodic dictation as depicted by Karpinksi resemble something that can be turned into an experiment, as well as a computational model. 
It's basically an experiment where we have in person level predictors and melodies with different item level difficulty. 
This dissertation seeks to explore the degree to which methodologies from cognitive psychology and computational musicology are able to further this literature and take the next logical step in terms of understanding aural skills.


```{r}
message("Diagram")
# library(DiagrammeR)
# 
# grViz("
#      digraph boxes_and_circles {
# 
#   # a 'graph' statement
#   graph [overlap = true, fontsize = 10]
# 
#   # several 'node' statements
#   node [shape = box,
#         fontname = Helvetica]
#   Individual ; Musical ; Cognitive ; Environmental ; Structural ; Experimental 
# 
#   node [shape = box] // sets as circles
#   WMC; Gf; CowanList; Musical_Training; Aural_Training; 
#   Interval_Structure; Times_Played; Tempo; AuralSkills
# 
#   # several 'edge' statements
#   AuralSkills -> Individual
#   AuralSkills -> Musical
#   Individual -> Cognitive
#   Individual -> Environmental
#   Musical -> Structural
#   Musical -> Experimental
#   Cognitive -> WMC
#   Cognitive -> Gf
#   Cognitive -> CowanList
#   Environmental -> Musical_Training
#   Environmental -> Aural_Training
#   Structural -> Interval_Structure 
#   Experimental -> Times_Played
#   Experimental -> Tempo
# } 
#       
#       ")

```

## Individual Factors

### Cognitive

Research from the cognitive psychology literature suggests that individuals differ in their percetual and cognitive abilities in ways that are not easily influenced by short term-training (cite) and that these abilities, when investigated on a large scale are predictive of a wealth of human behavior from RICHIE CITATIONS.
If literature exists that suggests that cognitive abilites are sucessful predictors of things related to something like academic achievement, it worth investigating the extent that these abilities might play when modeling melodic dictation.
This is also important to understand because if we were to find out that something as simple as general fluid intelligence was a strong predictor in musical tasks that we are grading people on, it would be pretty unfair to do since we are then basiclly grading people on genetic factors beyond their control, as well as environmental factors shown to have some sort of effect on IQ (Richie paper again).
Recenlty there has been a surge of interest in this area (nancy rogers, LVH, utah guy, karinkski icmpc, form at SMT) probably due to the fact that educators are picking up on the fact that cognitive abilities are powerful predictors and need to be understood since they ineveitably will play a role in pedagogical settings. 

Before diving into a discussion regarding differences in cognitive ability, I should note that sometimes ideas regarding differnces in cognitive ability been hostily recieved (citation against people talking about IQ) and for good reasons.
Research in this area can and has been taken advantage to further dangerous ideologies (Bell Curve), but often arguments that assert meaningful differences in cognitiev abilites between groups are founed on statistical misunderstandings and have been debunked in other literature (measure of man).
With that cleared out of the way, it is very hard to mantain a scientific commitment to the theory of evolution (Darwin) and not expect variation in all aspects of human behavior, with cognition falling within that umbrella.

Attempting to measure aspects of cognition go back over a century.
Even before concepts of intelligence were posited by Charles Spearman and his conception of _g_ (Spearman, 1904), scientists were intersted in finding links between an individual's mental abilities and some sort of physical manifestation.
This area of research was pretty dark and kind of implicitly was all about validating preconceutalized ideas that people had on the superiority of peoples, with white dudes always comign out on top.
For example, THIS GUY WHO TRIED TO QUANTIFY GREATNESS
Also this guy who basically measured people's skull sizes.
But of course this stuff is not meaningful at all, especially when the dependent variable in this was so subjective and constrained by a culture where one ruling people (white dudes) had all the power.

I only mention this because this line of thinking was co-opted by the American herediterian school of IQ (page 187 in Gould), where people that were after the same sort of idea (superiority of white people) basically took ideas of Alfred Binet, one of the first people to begin to systematically investigate cognitive ability in children at request of the french governement so that children who were, what today we would call learning disabled, could be identified and given special attention.
Binet also took a lot of inspiration from Broca, WHO I TALK ABOUT ABOVE ON SKULL SIZE.

Bient was the initial developer of the idea of an intelligence quotient (divide mental age by chronological age then multiply by 100) and provided one of the first ways to attempt to measure something that was not capable of being manifested in the phsysical world. 
Around the same time have people like Cyrial Burt and Charles spearmean developing new theories of intelligence based on the reification factor analysis and calling it g that is based on solving problems without prior knowledge. 

sentence here about g and the postive manifold

Of course took this aside to talk about that basiclaly Binet and Spearman's ideologies about what can be measusred still represent two of the largest schools of thought on ways to meausre cognitive ability.
On one hand there idea that cognitive abilities are based upon a steady growth of incoming information that someone is able to manipulate once they retrieve from long term memory, the other hand is that in addition to that there is some sort of construct in the mind that differs between people that can singularly refelect their intelligence, often referred to as g. 

Basic assumption is that there is something in the brain here where differences will lead to different behaviors. 
Without detailing entire histories of this line of thought, Binet basically turned into an argument for general crystalized intelligence, or DEFINITINO HERE (citation).
The Spearman, Burt strain of thought evolved into the _g_ school, and recent reserach has suggested that the concept of _g_ basically is statistcally equnivlient to idea conceptualized as general fluid intelligence (cite that in POT).
Both of these constructs are powerful predictors on a large scale, but they don't explain the entire picture.

Another large area in the field of cognitve psychology is the area of working memory capacity.
As noted in Cowan 2005, what the term refers depends on the framework that is being used, but generally refers to the amount of information that can be acvtively held in concsionus representation, akin to short term memory, but with some important caveats discssed below. 
In additon to concepts of intelligence, be it Gf or Gc, the working memory capcity literature has done a lot of the heavy theoretical lifting, and after reviewing it we will have a much better idea of how once you decide about how you conceptualize it, then it's helpful. 

Given this brief background on cognitive ability, going to now dive deeper into both working memory capcity, as well as general fluid intelligence (avoid calling it _g_ for good reasons) and review literature where these have been discussed as they relate to research on music perception, thus being related to melodic dictation, a skill that you need to percieve music to be able to do? 

### Working Memory Capacity

Working memory is one of the most investigated concepts in the cognitive psychology literature.
According to Nelson Cowan, the term working memory generally refers to 
> the relativly small amount of information that one can hold in mind, attend to, or, technically speaking, maintain in a rapidly accesible state at one time. The term working is mean to indicate that mental work requres use of such informaiton. (p.1]) [@cowanWorkingMemoryCapacity2005]

The term, like most concepts in science, does not have an exact operant definition and reserachers throughout the past century have conceptualized differently.
While there is no universally recognized first use of the term _working memory_, researchers began to postulate that there was some sort of system that mediated the all of the incoming sensory informaiton with the world with the information in long term storage. 
Summerized in [@cowanWorkingMemoryCapacity2005], one of the first modal models of memory was proposed by BROADBENT 1958 and later expaneded by ATKINSON AND SHIFFREIN 1968.
As seen in FIGURE X, both models here posit incoming information that is then put into some sort of limited capacity store.
These modal models were then expanded on by Baddely and Hitch [@baddeleyWorkingMemory1974] in their 1974 chapter with the name _Working Memory_, where they proposed a system with an Central Executive module that was able to carry out active maintance and rehearsal of information that could be stored in either a phonological store for sounds or a visual sketchpad for images.
Later revisions of their model also incorporated an episodic buffer (BADDELY 2000) where the modules were explicitly depicted as being able to interface with long term memory in the rehearsal processes.
The model has even been expanded upon by other researchers throughout it's lifeteime
The most notable and relevant to this study by is by [@berzWorkingMemoryMusic1995], who posutlated adding a musical rehearsal loop to the already established phonological loop and visual spatial sketchpad.
While Berz is correct in asserting that the nature of storing and processing musical informaiton is probably different to that of words or pictures, it does introduce the theoretical problem of multiple stores which has been addressed by other researcehrs.

In addressing the problem of explicitnlgy stating which rehearsal loops do and do not exist, Nelson Cowan have proposed other models (COWAN 1988, COWAN 1999) such as the Embeded Process Model which do not claim the existance of any domain specific module (e.g. positing a phonological loop, visual spatial sketchpad) but propose an exhaustive model that did away with the problem of asserting specific buffers for new types of information. 

In Cowan's own words:

> Could put quote on page 42 here if needed analogy that expains it well.

The system is depicted in the bottom tier of TABLE X, and conceptualizes the limited amount of information that is readily availie as being in the focus of attengion, with activated sesnory and categorical features of what is in the focus of attention to be nearly acccesible.
Moving further from the locus of attention is long term memory, whose content can be turned to by using the central executive to access non immediatly availible information. 
In contrast to the modular approaches, Cowan's framework does not require the researhers to specifiy exactly how and where each the incoming information is being storied which makes it advantagous for studying complex stimuli such as music and melodies. 

In addition to having multiple frameworks for studying working memory capacity, there is also the problem of if there are limits to the working memory system, often referred to as the working memory capacity.
Most popularized by Miller in his famouns 1956 article, he suggests out of jest that the number 7 might be worht investigating, which has been used as a point of reference for many researchers since then that have not critically engaged with the article.
Miller has even gone on record as noting that using 7 (plus or minus 2) was a rhetorical device used to string together his speech (CITATION) and that "quote from himn on htat".
Nevertheless, while probably bougus, this number has been since reduced to about 4 (COWAN CITATION) and research around this has been discussed and summerized at lenght (COWAN 2005) and has been arrived at by using complex span tasks. 

Clearly an individual's ability to take in sensory information, maintain it in memory, actively carry out other tasks (like noting that melody) are almost identical to taks of working memory capacity.
Worht noting here that these are not going to be one to one mappings

* Music is always sequential 
* Music is processed hierachcially
* Other things from that cowan table.

Thhis all said, WM liteature has done a lot of the theoretical lifing, and WMC is important thing to consider.

Look how Berz ends his article

Important to note here that still area worht looking at because as Berz notes in the last sentence of his article that

> Individual differences portrayed in some music aptitude tests may [sic] represent not talent or musical intelligence but ability, reflecting differences in working memory capacity. p. 362

Since it's publication, some studies have looked at this.... 

#### Papers that suggest WMC plays a role

* [@nicholsScoreOneJazz2018]
* Halpern paper on conductors
* Sight reading paper 

Summerize 

### General Intelligence

As discussed above gf has a long history, some good some bad.
Thing is that it can be really predictive of many things and people def do try incoproate it into music research.

One of the big problems with this is establishing effects of causality looking at music.
Could be that factors outside of music play a role like persanal views of ability (Daniel paper), socio economic status, and personality.
And field is even big enough to have null results (include that catty comment of glenn schellenberg)

* Stuff on mozart effect 
* Whole chapter from Schellenberg
* Swaminithan papers

#### Papers that suggest GF plays a role

### Environmental 

### Long term memory and corpus with implicit

Standing in contrast to factors that individuals do not have a much control over such as the size of their working memory capapacity or factors related to their general fluid intelligence, most of the factors we believe contribute to someone's abililty to take melodic dictation have to deal with factors related to training and the envirionment.
In fact, one of the tacit assumptions of getting a music degree revolves around the implictly held belief that with delibrate and attentive practice, that an individual is able to move from novice to expertise in their chosen domain.
The idea that time invested results in beneficial returns is probably best exemplified by work produced by ANDERS ERICKSON 1993 that suggests that performance at more elite levels has to do with delibreate practice.
Below I review literature that supports this argument, since it's no doubt that someone has to engage in something to be good at it. 

### Musical Training 

It almost seems redundant to review literature in support of music practice leading to better results.

* List of those papers here

### Aural Training 

* Dictation has not been that well researched [@furbyEffectsPeerTutoring2016] 
* people try lots of things, not much evidence for peer tutoring [@furbyEffectsPeerTutoring2016]
* ISOLATION OF RHTYM AND MELODY
- Banton 1995
- Bland 1984
- Root 1931
- Wilson 1954
* LISTENING BEFORE WRITING
- Banton 1995
* RECOGNIZING PATTERNS
- Banton 1995
- Bland 1984
- Root 1931
* SINGING SILENTLY WHEN DICRTAING
- [@klonoskiImprovingDictationAuralSkills2006]



### Sight Singing 

* [@fournierCognitiveStrategiesSightsinging2017a]  - catalogugig different strategizes used in sight signings
- four main categories
- 14 subcategories


### To Sort

* Harrison 1994
*  
  
## Musical Factors


## Structural 

Clealrly strutures also will play a role in this. 


* MEYER 1956
* HURON 2006
* [@margulisModelMelodicExpectation2005]

* Obviously not an exact match with perception CITE SCHENKER 

### Not first to model structure

* Long found that lenght, tonal structure, contour, and individual traits all contribute and also found that structure and tonalness (AS COMPUTED HOW) are good predictors [@longRelationshipsPitchMemory1977]
* Problem with long is that they eliminated people who werre bad singers for the example, this is at odds both with intutiion of representatino not being perfect mapping to singing, and has been DEMONSTRATED BY THESE PAPERS BY PETER PFORDRESHER.



### Early papers of Ortmann

* [@ortmannTonalDeterminantsMelodic1933]

### Papers from Mid 20th Century

( got these from paney 2016)

* EFFECT OF TEMPO HOFSTETTTER 1981
* TONALITY DOWLING 1978
* TONALITY LONG 1977 (already mentioned somehere else)
* OURA AND HATANO 1988
* TONALITY [@pembrookInterferenceTranscriptionProcess1986]
* SIZE OF INTERVALS [@ortmannTonalDeterminantsMelodic1933]
* CONJUNCT VS DISJUNCT MVT ORTMAN 1933 PEMBROOK
* length of the melody (Gephardt, 1978; Long, 1977;
                        Pembrook, 1986), 
* number of presentations of the melody (Hofstetter, 1981; Pembrook, 1986),
* context of the presentations (Schellenberg, 1985)
* participants’ musical experience (Long, 1977; Oura & Hatano, 1988; Schellenberg, 1985; Taylor & Pembrook, 1983), 
* Familiarity with the style of music (Schellenberg, 1985).
* [@taylorStrategiesMemoryShort1983] Extensin of Ortmann and looked at more musical skills, shows ways to suggest scoring simple melodies


* [@ouraConstructingRepresentationMelody1991a] - sampel of 8 but pretty much suggests that there is quick pattern matching that happens as it is drawn from LTM, 
* [@paneyEffectDirectingAttention2016] - if you direct attention, people do better at melodic dictation. said the next four were the only things looking at dictation since 2000
* Gillespie 2001 - HOW DO PEOPLE SCORE MELODIES
* Norris 2003 achievement and melodic dictation and sight singing CLEARLY A RELATIONSHIP
* [@pembrookSendHelpAural1990] - 
  * [@paneyTeachingMelodicDictation2014] interviewed HS teachers on how they teach it for APi

* [@pembrookInterferenceTranscriptionProcess1986] - discussin here wher used tonality, melodic length, and motion, interesting also restricted melodies to ones you can sing. Found length, tonality and motion to be signficant at 13 3 1 variance. Though seems like with this there is a lot of chance for type I error and IS THERE EVEN ENOUGH INFO HERE IN THE PAPER TO RECREATE IT ALL. Also claims that people can hear about 10--16 notes, tho DJB would add this is obviously dependent on what i refer to as musical experimental factors and would not make sense to carry this logic forwad without more constraints. 

### Buonviri Papers

* [@buonviriEffectsMusicNotation2015; @buonviriEffectsPreparatorySinging2015; @buonviriEffectsTwoListening2017; @buonviriExplorationUndergraduateMusic2014; @buonviriMelodicDictationInstruction2015; @paneyTeachingMelodicDictation2014]

### Caveat about dilberate practice and talent

Also should mention here that clealrly not a perfect one dimensional model where effort equals results.
Simple thought expeiment that hard work does not always equal sucess in that there are sucssfull people who have not worked hard and very hard workers who do not experience sucess in what they do.
Additionally people need to keep up the skills they have, insert hilarious quote here from potter not believing that people didnt keep up their melodic dictaiton skills and show that they are compartmentalized [@potterIdentifyingSucessfulDictation1990]
This of course does not nullify any findings on delibreate practice, but goes to show that the whole thing is kind of complicated. 


### Recent Computational Musicology Work papers and findings

START HERE FOR WORD COUNT
As noted above, in following studies XYZ, people have looked at musical features before me. 
Since then there have been a lot futher strides in the world of computational musicology.
SAY THAT IN CHAPTER 4 YOU ARE GOING TO be discussing history of computational musicology.


#### Static Views of Computational Features/ FANTASTIC


* Müllensiefen, Halpern & Wiggins (mullensiefen 2014)
* Stewart, Müllensiefen & Cooper FIND THIS, related ACTUAL MBEA 
* 

* Sucessful at predicting court case decisions Müllensiefen & Pendzich, 2009 
* (Kopiez & Müllensiefen, 2008) If Beatles songs of revolver can see what gets to the top 

* M4S Corpus Müllensiefen, Wiggins & Lewis, 2008
  - 14 K MIDI recordings
  - 1950-2006
  - Complete compositions
  - Some performance timings
  
* Melodic Contour Müllensiefen, Bonometti, Stewart & Wiggins, 2009;
* Melodic Contour Frieler, Müllensiefen & Riedemann, in press
* Müllensiefen & Wiggins UNDER REVIEW COUNTOUR

* PHRASE SEGMENTATION Pearce, Müllensiefen & Wiggins, 2008;

* Harmonic Content Mauch, Müllensiefen, Dixon & Wiggins, 2008;
* Harmonic Contetn Rhodes, Lewis & Müllensiefen, 2007
* Melodic accent structure Pfleiderer & Müllensiefen, 2006;
* Müllensiefen, Pfleiderer & Frieler, 2009 MELODIC ACCENT STUCTURE

ENTER FANTASTIC

FROM FANTSTIC

Phrase summary features that summarise the content of a melodic phrase, conceptually similar to the features that Steinbeck (1982) proposed but incorporating as well recent knowledge and techniques on tonality induction and melodic contour.
Repetition features that measure the repetitiveness of short melodic-rhythmic sequences or motives (called m-types) which are the building blocks of melodies. These features are mainly inspired by characteristic text constants from computational linguistics that describe the frequency distribution of words in written text (see Baayen, 2001).
Features based on the frequencies and frequency densities of phrase summary features in a corpus of pop music. These features build on the assumption that the frequency with which melodic features appear in real music are very important for music cognition (Huron, 2006).
Features that are based on the corpus-derived frequencies of m-types as building blocks of melodies. These features are motivated by the important role that word frequencies play in text information retrieval and text categorisation (Landau et al., 2007) and verbal memory (Tse and Altarriba, 2007).

* open soure packge for computaitonal anlaysis
* XX features
* Comes from stats, music thoery, music cognition, computaitonal Linguatstic (GET THAT CITATION), MIR
* Summary Features
* M-type features
* Context medoling via intergration of a orpus for 2nd order features

OTHER PEOPLE WHO HAVE DONE THIS

Folk music

* Bartok 1936?
* Bartok and Lord 1951
* Lomax 1977
* Steinbeck 1982
* Jesser 1992
* Sagrillo 1999

* GET AND READ PAT SAVAGE ARTICLE

Popular Music

* Moor 2006
* Kramarz 2006
* Furnes 2006
* Riedemann ????

Computational Musicology

* Eerola eta al 2007  and 2007
* McCay 2005
* Huron 2006
* Frieler 2008
* JAZZOMAT PROJECRT OUTPUT

GOOGLE SCHOLAR FANTASTIC CITERS

* ROLE OF FEATURE AND CONTEXT IN RECOGNITION OF NEW MELODIES MULLENSIEFN AND HALPERN 2014
* EARWORMS FROM THREE ANGELS WILLIAMSON AND MULLSIEFN 2012
* CORPUS ANALYS TOOLS FOR COMPUTATIONAL HOOK DISCOVERY VAN PALEN BURGOYNE BOUNTORDIS 2015
* DISSECTIN AN EARWORM MELODIC FEATURES PREDICT IMI Jakubowski 2017

* MODELING MELODIC DISCRIMINATION TASKS HAARPSION 2016
* INTERRRATER AGREEMENT IN MEMORY FOR MELODY AS MESUARE OF SIMILARITY HERFF DEAN OLSEN 2017
* MEMORY FOR MELODY INVEASTIAGTING HTE LINK BVETWEEN EPXERIENCE HERFF 2017
* THE MUSOS TOOLKIT -- COMPUTER ASED OPEN SOURCE RAINSFORD PALER PAINE 2018!!!!!
* Perception of Leitmotves in Richard Wagner's Dr Ring des -- BAKER 2017
* Brown Collins Laney COMPUTAITONAL MODELS OF SYTLISTIC COMPARISON ???


#### Dynamic 

* PEARCE 2005 CITATION
* THINGS FORM THAT 2012 REVIEW ARTICLE 
* PAPERS HERE THAT SHOW HOW IDYOM IS A GOOD MODEL OF THIS 
* SHANNON CITATION , MAYBE OLDER OTHER PAPERS TOO THAT TALK ABOUT SHANNON ENTOROPY

## Experimental

* Could also put things like timbre into here, also relevant to this


### Brief discussion on Individual and Envirnoment Interactions

Thinking about how all of these parameters contributes makes sense to a certain degree
Could imagene the extereme case of each of these either helping or hindering someone's ability to think.
Additionally could be the point that things interact with each other.
And on top of that we have the idea about levels of Explanation
  - SEE THAT WITH WIGGINS
  - SEE THAT WITH HOW COWAN 2005 ends his book 

## Modeling and Polymorphism of Ability 

Important here to note that unlike Harrison 1994, not really appropriate to conceptualize this as latenta bility.
Very easy in statistical terms to talk about latent variables and be able to talk about lots of variance predictied.
But problem with any sort of model like that or model of musical sophistcation is that it has same fate as g.

QUOTES HERE FROM MS paper on latent variables 

Musicianship as a concept of something ot measure when talking about this one little task with relative lack of concrete evidence for it's transfer, need to return back to a process model of melodic dictaiton.

### Polymophic, component process makes you think about things in models

Going to say here that LVs are bad and that need to adopt a more polymorphic view of musicianship as advocated by

* Levitin XXX
* Peretz 2006

## Conclusions

In this chapter I have first described what is melodic dictation, Karpinki's verbal model of it, noted what the things were that were missing from this model as a stepping off point, then went on to suggest a taxnomy of these based on what already has done. 
Suggest that there are both individual as well as musical features that are at play here.
Individual features can be either cognitive, sort of fixed, or environemental, having do with training.
Musical features can be either structural, or experimental like how you play the melody.
None of these are nessecariy hard and fast divisions, and certainly there are going to be some interactions between any and all of the levels.
Clearly a very great question and given how much we look at it, want to know more about this complicated network of proccesses. 
Given this laundry list of factors, now going to explore the individual parameters in Chapter 3, the musical chapters in 4 and 5, as well as how they would come together in chapter 6.
Also will then go into more detail about many of the papers that I mentioned. 
Really there should be a chapter 7 where after thinking about all of this I put together a computational model that succcedes at incorporating a polymorphic view of musical trianing by making a proces model inspired by Karpinki that is able to be both a research and pedagogical stepping off point for futre reserach on modeling melodic dictation.


### Clearly we have factors that are thought to contribute, need to investigate them in full with each chapter
### Not before first looking at why we are doing it in the first place (--transition to Chapter 2)
