# Computation Chapter

--- ISMIR 
; symbolic music processing
; computational music theory and musicology
; cognitive MIR
; datasets 
; evaluation beyond just notes
; training and education application
---

## Rationale

Music theorists use their pedagogical experience and intuitions to build the appropriate curricula for their aural skills pedagogy.
Teaching aural skills typically starts with providing students with simpler exercises, often employing  a limited number of notes and rhythms, and then slowly progressing to more difficult repertoire. 
This progression from simpler to more difficult is evident in aural skills text books.
Of the major aural skills textbooks such as the OTTMANN, the BERKOWITZ, KARPINSKI, CLENDENNING MARVIN, DOBREA CLELAND, each is structured in such a way that musical material presented earlier on in the book is more manageable than that near the end.
In fact, this is true of almost any ETUDE book: open to a random page in a book of musical studies and the difficulty of the study will most likely scale accordingly to its relative position in the textbook.
But it is not a melody's position in a text book that makes it difficult to perform: this difficulty comes from the structural elements from the music itself.

Intuitively, music theorists have a general understanding of what makes a melody difficult to dictate.^[I find it safe to assume that more complex melodies are more difficult to dictate As I will demonstrate in this chapter, a melody's complexity and difficulty to be dictated are closely related. For that reason, I will use the term complexity as a proxy for its ability to be  dictated.] 
Factors that might contribute to this complexity could be attributes such as the melody's note density, the intricacies of the rhythms involved, the scale from which the melody derives, or even more intuitively understood factors such as how tonal the melody sounds.
Although given all these factors, there is no definitive combination of features that perfectly predicts the degree to which theorists will agree how complex a melody is.
In many ways, questions of melodic complexity are very much like questions of melodic similarity: it depends on both who is asking the question and for what reasons (CITE SELF).

Looking at the melodies presented in Figures X and Y, most aural skills pedagogues will be able to successfully intuit which melody is more complex, and presumably, more difficulty to dictate.

* FIGURE 1 -- Melody with 8 Bars, functional accidentals (V/V, V/IV)

* FIGURE 2 -- Same sets of notes rearranged 

While I reserve an extended discussion of what features might characterize why one melody is more difficult than the other to dictate for below, I assume that these melodies do differ in a fundamentally different way when performed in a similar fashion.
Additionally, many readers of this dissertation can probably draw from anecdotal evidence of their own as to how student's at various stages of their aural training might fair when asked to dictate both melodies.
For some, melody Y might be overwhelmingly difficult.

In fact, it might be overwhelmingly difficulty for the vast majority of people.
Student are quick establish if they belie that a melody they are being tested on is too difficult, and importantly from a pedagogical standpoint, we as educators need to be able to know how difficulty melodies are given our students in order to asses a degree of fairness in our grading of student's performance.
While of course with each student there are inevitably many other variables at play ranging from personal abilities to the goals of the instructor in the scope of their course, yet there are intuitive benchmarks that students are expected to be able to complete throughout their education.
As students progress, they are expected to be able to dictate more and more difficult melodies, yet exactly what makes a melody complex is often left to the expertise and intuition of a theorist.

In this chapter I examine how tools from computational musicology can be used to help model an aural skill's notion of complexity in melodies.
First, I establish that theorists agree on the differences in melodic complexity using results from a small survey of XX theorists.
Second, explore how both static and dynamic computationally derived measures can be used to approximate an aural skills pedagogue's intuition. 
Third and finally, I use evidence afforded by research in computational musicology to posit that the distributional patterns in a corpus of music can be strategically employed to create a more linear path to success among students of aural skills.
I demonstrate how by combining evidence from the statistical learning hypothesis, the probabilistic prediction hypothesis, and a newly posited distributional frequency hypothesis can explain why some musical sequences in a melody of a certain complexity are easier to dictate than others.
Using this logic, I then create a new compendium of short melodies, sorted by their perceptual complexity, that can be used for teaching applications.

## Agreeing on Complexity

Returning to melodies X and Y from above, an aural skills pedagogue most likely has some sort of intution of which of the two melodies would be easier to dictate.
Melody X exhibits a predictiable melodic synatax and phrase structure, the chromatic notes resovle within the conventions of the Common Practice period, and many of the melodic motives outline and imply a harmony based on tertian harmony.
On the other hand, Melody Y's syntax does not comform the the conventions of the common practice music and does not imply any sort of underlying harmony.
The durations of the rhythms appear irregular and the melody implies an uneven phrase structure.
Yet both melodies X and Y have the exact same set of notes and rhythms.
Though despite these content similarities, it would be safe to assume that melody X is probably much easier to dictate than melody Y assuming both were to be played at the same tempo and instrumentation. 

In fact, aural skills pedagoges tend to agree for the most part on questions of difficulty of dication.
To demonstrate this, I surveyed XX aural skills pedagogues who have all taught at least two years of aural skills at the University level asking them questions presented in TABLE X on a sample of XX melodies found in the BERKOWITZ.
The survey had questions that specficially were designed to gauge their appropriateness for use in a melodic dictation context.

Questions included:

---------------
Table 
1. What semester of aural skills do you think this melody is appropriate for?
2. How many times do you think this melody should be played in reference to your answer from question 1?
3. Please rate how difficult you believe this melody to be for the average second year undergraduate at your instiution.
4. How musical do you believe this melody to be?
5. Where in the melody (please list a measure number) do you think student's will have the most difficulty dictating the melody?
6. Is this a melody you would feel comfortable using in your own aural skill's class?
7. Could you dictate this melody now? 
----------------------

Overall, the sample exhibited a _____ degree of inter-rater reliability as measured by THIS STATISTICX^[Reference here about what is good and what is bad.]
Plotting the respondant's answers across the textbook, with the book progressing from less to more difficult, there is a trend of pedagoges to AGREE ON THE SIMPLER ONES THEN HAVE MORE DIAGREEMENT LATER ON? 
Central to my argument is a VERY LINEAR TREND of rating of complexity that correlate with both PAGE NUMBER from the textbook that it was drawn from, as well as an even better fitting model of THE EXACT NUMBER OF THE MELODY.
MORE DISCUSSION HERE AFTER LOOKING AT DATA.

Taken together, both anecdotal and the evidence for this survey suggest that aural skills pedagoges tend to agree on how difficult a melody is for use in an aural skills setting.
This sense of difficutly or complexity tracks as the book progresses, but to attribute the cause of a melody being difficult as its position in the book would be making a pretty hilarious error. 

--------- EDIT HERE
It is important to highlight that despite the level of agreement at lower levels of difficulty, even experts do not seem to agree on the appropriateness of melodies as they become more complex for classroom use.
Of course perfect levels of agreement are not expected, but due ot the fact that people need to be graded and assessed fairly on melodies, this level of disagreement is cause for alarm.
This level of disagreement might also help explain student's responses to aural skills pedagogy...
 
And to compound this problem, literature from psychology (Kanneman and Tversky, that medicice doctor study) importantly highlight the fact that it's important to be skeptical of expert opinions.
Drawing from the medical liteature-- a body of research where getting somethign wrong probably matters more-- have evidence of stuff happenign with heart attcks.
Undelrying logic being that people think they have the key, but really they do not.
And what solved this was a computaional problem. 
------------

The rest of this chapter investigates if similar computaionally derrived tools can help inform aural skills pedagogy.
In order to provide a sense of validity to the measure, I use the expert answers from the survey as the ground truth for the computational models.^[Do I have to explain what ground truth is?]

## Modeling Complexity

The ability to quantify what theorists generally agree to be melodic complexity depends on distilling complexity into its component parts.
Earlier, when comparing melodies X and Y, some of the features put forward that might contribute to this measure were features such as note density, the melody's rhythm, what scale the melody draws its notes from, and how expected the notes are, and how tonal the melody might be percieved. 
Some combination of these component features presumably make up the construct of complexity.

Attempting to use features of a melody to to predict how well a melody is remembered has a long history.
In 193X, Ortmann put forward a set of melodic determinants that he asserted predicted how well a melody was remembered.
These features such as a melody's repeition, pitch-direction, contour (conjunct-disjunct motion), degree, order, and implied harmony (chord structure) were deemed to affect the melody's ability to be remembered.

Pedagoges since Ortmann such as XYZ have expanded on this research and concluded that ________.
Using some sort of non-musical representation like a melody's contour is an abstracted feature of the melody.
Abstracted features of melodys assume some sort of suspended animation of listening meaning that what is abstracted has some sort of meaning that is related to the listening experience.
While if an abstracted measure maps directly to any sort of phenomenological experience in time, might be contested, these types of measures have been becoming more common in music psycholgy research.

* Sentence here about static and dynamic. 

### Static

An abstracted feature can be either a quantitative or qualitiative observable feature of a melody that is assumed to be perceptual to the listener, but often difficult to quantify with the traditional tools of music analysis.
Often, these abstracted features come inspired from other domains like computational linguistics.
To given an example of an abstracted feature, perhaps one of the most popular features in recent decades is the normalized pairwise variability index or nPVI (CITE).
The nPVI began as a measure of rhythmic variablility in langauge.
Shown in FIGURE X, the nPVI quantifies the xxx by the yyy in order to provide a metric that can be used as an approximation of the  perception that some langauges sound perceptually different. (GET MORE STUFF FROM ORIGINAL NPVI)
In lingusitics, the nPVI has been used to delinate stress timed langauges from something else...
Recenlty in the past x years, music science researchers have used the nPVI to attempt to investigate claims about the relationship between speeach and laguage (CITE ALL HERE).
While results are mixed regarding the nPVI's predictive ability and some people argue against nPVI (Nat), it does serve as a very good example of a static comuputationall derrived measure.
Just like taking the average weight in a population, the nPVI summerizes a phrase and importantly assumes that this measure is representive of the entire phrase the calcuation was performed upon.

or stuff here of meredith and that chapter. 

One of the most complete set of computational measures as applied to music perception comes from Daniel Mullensiefens' whole name FANTASTIC toolbox (CITE).
According to FANTATIC's techncial report, 

> "FANTASTIC is a program...that analyzes melodies by computing features The aim is to characterise a melody or a melodic phrase by a set of numerical or categorical values reflecting different aspects of musical structure. This feature representation of melodies can then be applied in Music Information Retrieval algorithms or computational
models of melody cognition." (pp. 4)

Drawing from fields both central and perphircal to music science, FANTASTIC computes a collection of XX features to analyze features of melodies and continues from a tradition of feature extraction in music research FROM Lomax (1977), Steinbeck (1982), Jesser (1990), Sagrillo (1999), Eerola and Toiviainen (2004) and since its release has been sucessful at ...... SINCE THEN.
Addittionally, FANTASATIC also provides a framework for comparing the features of a melody with a parent corpus from which the melody belongs.

Returning to the Aural Skills classroom, many of these features can be used to approximate the intutions of complexity as agreed upon by theorists.
Below, I SHOW A SERIES OF PLOTS WHERE the continously measured abstracted features of FANTASTIC are plotted against the measures of perceieved complexity and difficulty of expert aural skills pedagoges with their respective correlations in TABLE X.

* GIANT FIGURE HERE

* GIANT TABLE HERE

From this, it becomes evident that some features like __________ and ________ succede quite well in approximating the rated complexity measures, while others like __________ and ________ do not.
I suggest that the reasons that ________ measures are sucessful in explainig is because ___________________.

In modeling this problem univariatly (one v one), it quicly becomes evident that no single static measure from FANTASTIC is able to complete mirror that of the complexity measrues.
Following past research (HARRISON, ME, OTHER PAPER THAT I CANT THINK OF), I used a PRINCIPAL COMPONENTS ANALYSIS to distill a single measure of complexity from THIS THIS AND THIS, that I then plot against the ratings and show that using this measure in a regression context increases our correlatio/R2 up a bit.

Hopefully at this point, I can make the argument that I am getting quite close at fully explaining the variance in ratings.
Finally, using the features of FANTASTIC, I can also use a random forrest method (LIKE THESE DANIEL PAPERS) to use some machine learning methods to see what best explains this data.

USING A .... details of Random Forrest here......

And importanly..... Variable imporacne plot which works by running multiple models and seeing how much variance is accounted for when the model is left out.

We see that X Y Z are of highest importance, and this corroborates literature from other FANTASTIC measures that say XYZ.

This is important for pedagogy, this can be used to help provide objective measure of difficulty.
Can also be a starting point for work on linking these various features with listener response.
And thus help people desgin curricula and also then better understand human pecerception and role of melody in the aural skills clasroom. 

Though while sucessful at modeling, using various linear combinations of these static abstracted features still assumes that listerns experience melodies in some sort of perceptual suspended animation. 
In order to have more phenomenologically approriate model that incorporates computainoally derived features, it is important to turn to dynamic models of music perception.

### Dynamic 

The Information Dynamic of Muscic (IDyOM) model of Marcus Pearce is a computational model of auditory cognition that ... PEARCE 2018.
Unlike measures from FANTASTIC, that calculate summary statistics on melodies, IDyOM works by....
As mentioned in Chapter 1, IDyOM is based both on the SLH and PPH.
THey state....
Due to the fact that IDyOM makes its calculations based on a series of n-grams that the model learns, IDyOM is able to output measures of expectedness for each symbolic token used in its calculations.
As a model, IDyOM has been sucessful at modeling....
The findings are robust, yet the measures of information content based on Shannon entropy have yet to be used to actually quantify memory (even ala Miller 1956).

Using measures of IC from IDyOM is a novel application of the IDyOM model, but makes sense.
Literature from sequential learning notes that much of our learning for materials happens implicitly
This happens from both langauge and music.
Roherhimer reference
Margulis reference

If true, repeatitive stimuli are then easier to processly as they are going to tax memory less.
Lking aslo follow that IC measures of expctedness (if we assume expct are easier ot procecss) can be used in memory measure

Take for example the following two 8grams
THey are listed with their informaiton contnet.
One is the opening of this tune
The other is this really famous tone row

## Frequency Facilitation Hypothesis

Can see that both are sequences of eight notes, but one consists of more predictiable notes.
Can model this in terms of information content and as information accumulates over the phrase.
Intutivly, returning to logic from above, one will be easier to remember and dictate.
And This is due to processing fluency, thus less of a tax on memory.
So I am saying that you can use the IC measures of informaiton as actul measures of information.

More formally, the evidence can be summerized in what I am calling DFH.
Which states:

> 1. some sequences are easier to process, means they are more expected.
2. IC measures of expectancy can be used as prox for memory
3. Given sequence of N lenght melody, ease of dication which is loads on memory is relative to its degree of expectedness in IC and link it back to corpus by saying that it is relative to it's n-gram distribution frequency.


From this hypothesis, we derrive a couple of testiable predciitions that we can continue to
use tools from computational musicology and subsequestntly music psychology to answer.

### Distributional Patterns in Corpus

If this is true, we should see this again throughotu the corpus 
And If IC measures can be used as memory proxy bc of processing due to SLH and PPH, would follow that n-grams woudl be processed relative to their distribution in a corpus.
And they will have lower IC.
To show this I extract out of a corpus of 2 3 5 10 grams form both sides of frequency distribution of a corpus to present side by side show intuitive.

we can also plot this continously 

### Memory Facilitation 

Predictions here OR add in mini experiment that will be test for ISMIR paper.

go for further psychology experiemnts in this, 
lays basis for the computational model
and more direct pedagogical applicaitons are discussed below


### Peagogical applcation

Here is how you would do it pedagoically
If this is case, would mean that this is a new way to organize melodies in book.
Could instead list all melodies and have them as snippets.
Orgnize them like books in terms of ascending difficulty.
And this is how i have done it.
Samples from all the n-grams in this table

TABLE

Can find all the things in the back.
Would suggest learning these patterns as supplment to melody learning.
It would do the following things.
I list melodies in the back.
I would predict that if people learned this as supplment, they would do a lot better.
Also get rid of some sort of performance anxiety in little successes.

## Chapter Conclusions

In this chapter I have demonstrated how tools from computational musicology can be used as an aide in aural skills pedagogy.
After first establishing the extent to which aural skills pedagogues on various melody parameters, I then show how two families of computationally derrived features can stand in for a pedaguges intution.
First, using the FANTASTIC toolbox, I show how different combintations of static abstracted features can help explain theorists agreed upon complexity.
This first will help with selection of melodies and also provides insights as to which features of the melodies contribute most to percieved difficutly.
Second, I demonstrated how assumptions derived from the IDyOM framework can serve as a basis for the intutions of why smaller sequences of notes within melodies are more or less difficult to dictate.
Using the logic that sequences that are easier to process are more expected, and that computed measures of information content can be used as a proxy for memory, I show that it follows that given the sequence of an N lenght melody, the ease of dictaiton that it loads on memory is relative to both its degree of expectednes quantified in terms of informaiton content and link it back to hte corpus by linking THAT to it's n-gram distribbutional freuqency. 
This chain of thinking then allowed me to put forward a new sequence of melody segments that can be arragned, like other theory textbooks, in terms of their increasing complexiy.
I argue that using this smaller, snippit approach, will allow students to not be overwhelmed in their learning by taking a more linear path to dictation, before moving on to more more ecologically valid melodies.
I finish by disucssiong how this might be implemented in the classroom.


THER PEOPLE WHO HAVE DONE THIS

* look into Wiggins et al., 1993, for history of representation 

Folk music

* Bartok 1936?
* Bartok and Lord 1951
* Lomax 1977 ; Lomax, A. (1977). Universals in song. The World of Music, 19, 117–129.
* Steinbeck 1982 
* Jesser 1992
* Sagrillo 1999

* GET AND READ PAT SAVAGE ARTICLE

Popular Music

* Moor 2006
* Kramarz 2006
* Furnes 2006
* Riedemann ????

Computational Musicology

* Eerola eta al 2007  and 2007
* McCay 2005
* Huron 2006
* Frieler 2008
* JAZZOMAT PROJECRT OUTPUT

