--- 
title: "Modeling Melodic Dictation"
author: "David John Baker"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This dissertation explores both individual and musical features that might contribute to processes involved in melodic dictation."
---

# Significance of the Study

All students pursing a Bachelor's degree in Music from universities accredited by the National Association of Schools of Music must learn to take melodic dictation [@NationalAssociationSchools2018 Section VIII.6.B.2.A]. 
Melodic dictation is a cognitively demanding process that requires students to listen to a melody, retain it in memory, and then use their knowledge of Western musical notation in order to recreate the mental image of the melody on paper in a limited time frame.
As of 2018 there are 647 Schools of Music belonging to National Association of Schools of Music (NASM) CITE WEBSITE, meaning that hundereds of students every year will be expected to learn this challenging task as part of their Aural Skills education.
The logic being that as one improves in their abiliy to take melodic dictation, this practice of critical and active listening develops as a means to improve one's ability to "think in music" and thus become a more compotent musician.
While learning Aural Skills has been a hallmark of being educated within the Western conservatory tradition, the rationale behind both the how and why of aural skills is often thought of as being esoteric.
Throughout the past century, people have disagreed on exactly how one does go about learning a melody with different areas of research each attacking the problem from a different angle.

Despite its ubiqiquity in curricula within School of Music settings, research on topics pertain to how aural skills are acquired is limited at best.
[Citations here about the cosntant calls butler, klondoski, pembrook]
The fields of music theory and cognitive psychology are best positioned to make progress on this question, but often the skills required to be well versed ein ither of these subjects are disparate, published in other journals, and the research with overlap is scarce.
This problem is not new and there have been repeated attempts to bridge the gap between practioners of aural skills and people in cognitive psycholgy CITES.
Literature from music theory has establisehd conceptual frameworks regarding aural skills @karpinskiAuralSkillsAcquisition2000 and the relavint cognitive psychology literature has explored factors that might contribute to melodic perception (SCHMUKLER SYNERR 2016 2016), and there exists applied literature from the world of music education (CITES).

However, despite these siloed areas of research, we as music researchers do not have an a concrete understanding of exaclty what contributes to HOW individuals learn melodies (HALPERNBARLETT2010).
This is peculiar since "how does one learn a melody" seems to be one of the fundamental questions to the fields of music theory, music psychology, as well as music education. 
Given this lack of understanding, it becomes even more peculiar that this lack of convergence of evidence is then unable to provide a solid baseline as to what student in their aural skills classrooms can be expected to do. (Also something about we should really know this if we are going to grade people on this ability).
While no single dissertation can solve any problem completely, this dissertation aims to fill the gap in the literature between aural skills practitioners (theorists and educators) and music psychologists in order to reach conclusion that can be applied systematically in pedagogical contexts.
In order to do this I draw both literatures (music and science) in order to demonstrate how tools from both cognitive psychology as well as computational musicology can help move both fields forward.
Some line here about if we really want to understand what is happening we need to know about causal factors going on here and have experimental manipulation and things like making models of the whole thing or talk about what Judea Pearl thinks about the ability to do some sort of causal modeling with diagrams.
Great to rely on some sort of anecdoatal evidence, but if we are going to put things on the line with our education then we need to be able to make some sort of falsifiable claims about what we are doing.
Can only do that through the lens of science. 

## Claims about need to join the worlds of theory and pedagogy 

* [@davidbutlerWhyGulfMusic1997a]
* [@klonoskiPerceptualLearningHierarchy2000] - perceptual hierarchy, not enough info from aural skills training


## Chapter Overview 

In this first chapter, I introduce the process of melodic dictation and discuss factors that would presumably could play a role in taking melodic dictation.
The chapter introduces both a theoretical backgorund and rationale for using method form both computational musicology and congitive psychology in order ot answr quesitona bout how individuals learn melodies. 
I argue that tools for understanding this best because as we currently understand it, I see us operating in a Kuhnian normal science where much can be learned by just using the tools in front of us.
This chapter will clearly outline the factors hypothesized to contribute to an individual's abilit to learn melodies, incorporating both individual and musical parameters.
The chapter ends with a discussion some of the philosophical/theoretical problems with attempting to measure thigns like this (is it just a party trick?) and establishes that I will be taking a more polymorphic view of musicianship in order to answer this question.

The second chapter of my dissertation focuses on the history and current state of aural skills pedagogy.

Tracing back its origins to the practical need to teach musical skills back with Guido d’Arezzo, I compare
and contrast the different methodological approaches that have been used, along with their goals.

The third chapter discusses previous work that examines individual factors thought to contribute to one’s
ability to perform an aural skills task, and it will discuss results from an experiment contributing to a discussion of how individual differences could contribute to how a person learns melodies. 

Turning away from individual differences and focusing on musical features, in the fourth chapter I plan to
discuss how music researchers can use tools from computational musicology as predictive features of
melodies. 
Inspired by work from computational linguistics and information theory, recent work in
computational musicology has developed software capable of abstracting features thought to be
important to learning melodies, such as note density and ‘tonalness’ (Müllensiefen, 2009). 
Talk a bit about how this has been also looked at before in the music education community.

While these features have been used in large scale, exploratory studies, work in this chapter will discuss how these features could be used in controlled, experimental studies as a stand-in for the intuition many music pedagogues have when determining difficulty of a melody in a classroom setting. 

In my fifth chapter, I introduce a novel corpus of over 600 digitized melodies encoded in a queryable
format. 
This dataset will also serve as a valuable resource for future researchers in music, psychology,
and the digital humanities. 
This chapter begins with a discussion of the history of corpus studies, noting their origin outside of music, their current state in music, and their limitations. 
This chapter, encapsulating the encoding process, the sampling criteria, and the situation of corpus methodologies within the broader research area, will go over summary data and also talk about how it could be used to generate hypotheses for future experiemnts (n-gram stuff based on patterns) .

Lastly, in the final chapter, I will synthesize the previous research in a series of melodic dictation
experiments. 
Stimuli for the experiments are selected based on the abstracted features of the melodies
and are manipulated as independent variables based on the previous theoretical literature. 
I then model responses from the experiments using both individual factors and musical features in order to predict how well an individual performs in behavioral tasks similar to some of my previously published research (Baker & Müllensiefen, 2017). 
Here I also note important caveats in scoring melodic dictation, referencing some other of my own work on using metrics, such as edit distance (Baker & Shanahan, 2018), to discuss similarities between the correct answer and an individual’s attempts at dictation.
Results from the final chapter will be discussed with reference to how findings are applicable to
pedagoges in aural skills settings. 
Recommendations will be made building on current conceptual frameworks (Karpinski, 2000). 

<!--chapter:end:index.Rmd-->

# Theoretical Background and Rationale {#intro}

## What is melodic dictation? and Why?

Melodic dictation is the process in which an individual is able to hear a melody, retain it in memory, and then use their knowledge of Western musical notation to recreate the mental image of the melody on paper in a limited time frame.
For many, becoming profiecent at this task is at the core of developing one's aural skills.
This link between _ear_ training and it's implied transfer is tacit knowledge and to question the usefulness of this skill might even qualify as heretical.
Though researchers like Klonoski has raised important questions like "What specific deficiency is revelaned with an incorrect reponse in melodic dictaiton settings?" [@klonoskiImprovingDictationAuralSkills2006]
It is this ability to think _in_ music that h

* [@schumannMusikalischeHausUnd1967] - dumb schumann quote
* 1934 quote about hear with eye, see with ear [@smith1934solfege]
* McGaughy 1961 " qualified musicians must develop reading, singing, and [italics added]
notational skills in order to achieve acuity of aural perception and to
make effective use of that acuity" (p. i)."

* CUDDY 1982 ITS JUST REALLY HARD TO TALK ABOUT 

Examples about older people who have talked about it.

Despite the century old rhetoric on the importance of developing one's ear, exactly how an individual goes about improving one's _ear_, or even coming up with a concrete, operationalized definition of what one's _ear_ actually is has yet to be fully defined.
A large part of this probably stems from the fact that many of the skills that are generally grouped under the curricular umbrella of aural skills are extremely complex cognitive processes that are hard to detail at their every step.
These skills range from being able to identify basic features of the acoustical properties of music, to melodic dictation, polyphonic dictation, harmonic dication, error identification, hearing large scale form, sight singing, sight reading on an individual's primary instrument, as well as score reading, and any keyboard skills that aid in these tasks.
While this assortment of abilities might seem like a aural potpourri, [@karpinskiAuralSkillsAcquisition2000] has taxonimized the aforementioned list into two larger categories of Listening Skills and Reading and Performing Skills.
In his seminal text, he establishes multiple helpful that I will refer to throughout the course of this dissertation.


Stuff about the truly aural skills.

In addition to his bifurcation of arual skills into Listening and Reading/Performing skills, Karpinski devotes an entire chapter to the study of melodic dictation, providing a verbal model for how he describes the component parts and process as a whole.

### Describe process

* Need to talk about chunking 

Karpinski's chapter on Aural Skills culminates in a flowchart, Figure 3.1 in his textbook reporduced below, that schematizes how he believes the process to work. 

Upon listenign to a melody,

### Karpinski schematic of it (as verbal model, problems)

Karpinski's schmatization of melodic dictation can generally be conceptualized as process that consists of the following four steps:

* Hear
* Remember
* Understand
* Notate

For Karpinski, most of the cognitive action happens in the understand process, which is the only subprocess that he groups into two differnt sub-processes: one foo understanding the temporal aspects of music (e.g. pulse, meter, rhythmic proportions) and another for understand the pitch parameters (e.g. tonci, scale degree of starting pitch, scale degree of subsequnt pitches).
The process is looped over with every hearing, and Karpinski suggests that the listener will use some sort of chunking of melodies in order to hear the melody and to then notate it. 

#### Verbal model, has problems, OK for pedagogy

As a verbal model, Karpinski's model of dictation makes sense and breaks down a very complicated cognitive process into discrete, sequential steps.
This model, whether or not Karpinski intented it to be an actual cognitive model, I don't know, assumes serial processing of information and does not specify any of the actual parameters for each of the steps.
This model serves as a great stepping off point for this dissertation, and its good for me that he didn't actually specificy any of the actual parameters, he just said certain things happen and gave an approximate order of the whole thing.
He talks about a lot of the parameters leading up to it all,
Even talks about things like representation and other paramters that are going to influence it all.
Did not attempt to pin down any of the exact parameters of his model, but this is just me wanting to forshadown Chapter 6 where I take each of these issues and implement them in a computational model. 
While covering many bases, one of the problems with using a verbal model as opposed to a computational one is that by not specificying exaclty what happens when and how everything is represented, the model can manifest itself in a multiude of different ways.

Take for example the often cited model of working memory by Alan Baddely and Grahm Hitch which posits a modular view of workign memory capcacity [@baddeleyWorkingMemory1974].
As discussed in CITE, although the model only has X amount of distinctive systems, the fact that they left it to be a verbal model of memory, and did not tack down exactly how each parameter functions, when built as computational model actually ends up yielding 156 different models. 
While I will reseve discussing how many possible models might exists as derrived from the Karpinski for Chapter 6, it is suffice to say that clearly establishing the degree to which part of the model contributes in concrete way only helps with furthering the literature.


#### Verbal model, no individual differnces tho literture to suggest

One thing that is lacking in the Karpinski model are any sort of individual differences.
A wealth of literature from music perception and cognition suggests that musical training has effects on how people perform in musical tasks TRAIN OF CITATIONS HERE.
Given the evidence that individual differences play a role here, there should be some sort of way of incorporating them into a model of melodic dictation. 

#### Computational model to be introduced

From an empirical standpoint, both the task as well as the process of melodic dictation as depicted by Karpinksi resemble something that can be turned into an experiment, as well as a computational model. 
This dissertation seeks to explore the degree to which methodologies from cognitive psychology and computational musicology are able to further this literature and take the next logical step in terms of understanding aural skills. 


* Need to talk about extractive listening in the melodic dictation process
* Also need to talk about how if you look at melodic dictation as active process... helpfullllllll?


Find Karpinksi 1990 on his model ......

Given work from Karpinksi, we know that the following factors play a role in this extractive listening process 

* Hearing -- actual playing of melody
* Short Term Melodic Memory 
* Extractive Listening 
* Chunking 
* Meter and Rhythm
* Rhythm Solimization and Understanding
* Pitch -- representation and contour, solimization
* Notation -- clealry need to know how it all works 
* Tempo
* Length and Number of Playing
* Duration between Playing 

* he puts forth chunking formula on page 99

* is it OK to say that he leaves out difficulty of melody
* is it OK to say that he leaves out individual differences

* is rhthmic solimization just the same as LTM 

### Clearly this is psychological problem with different item level difficulty   

When viewed from a pedagogical stand point, espcielaly given how litle time people have, it would basically be impossible to attend to each of these things in a gradient fashion in the standard 15 week semester that people have. 
When people teach this, need to rely very much on intuition and basically adjust to the level of your class and syllabus and whatever on the fly in order to convey the most amount of musical materials possible. 

Conversly, when viewed from an experimental standpoint, each of the above mentioned processes is bascially an experimental parameter waiting to be investigated.
Additionally, the process that is put forth by KARPINSKI 1999 provides a stepping off point for positing some sort of comutational model.
Going to add substatinally to it in that going to take into account both how difficulty the melodies are, something we  have intiutive understanding of, but could be operationalized, and also going to try to model individual differences based on factors that prior literature would suggest are different in individuals and should be considered in any sort of modeling going forward. 
In addition to these above parameters discussed by Karpinski, now review other factors that could then contribute to this process.

#### Individual Factors to contribute 

From an individual stand point, can bifurcate factors broadly into *cognitive factors*, or factors of people that are relatively consistent over people or basically like fixed effects things (use definiton of what is a fixed effect); and the other side of this would be things that would have to be delt with that change with training and exposure. 
Going to refer to this second set of things as *Environmental* factors. 
Is there a better way to talk about this as nature vs nurture.
Addiitonally need to then mention that there are of course epigenitic factors where both of these parameters might interact with one another. 
For example, might then imagine that someone with higher cognitive abilitty, lots of training that was put forward by their parents, as well as tons of musical training, and personality traits that are more likely to learn more (daniels paper on that) might be different in terms of resutls than someone with lower cognitive abilities, no training, low SES, and a general inclination not to even take music lessons. 
While obvious, what will eventually be of interest is the degree to which each of these things contributes to the final models.
Also gives us a better idea about pedagogy and what not. 

#### Musical factors to contribute

In addition to differences at the individual level, there are also musical level characteristics.
In this category it is also worth taxonimizing the musical characterstics into two categories as well.
On one hand we have the structural aspects of the melody itself.
These are aspects of the melody that would remain invariant when written down on a score.
Reading from left to right, would be things like range, key, time signature, intervals, amount of notes, contour of the melody, tonal properties, standardized note density.
Then the other side would be musical features that I am going to deem as experiemntal features of the melody.
These are aspects of the structure of hte melody that you can then warp within the context of a melodic dictiation such as tempo, which then refelcts note density, timbral qualities, how many times the melody is played, the space between hearings. 
This is not a categorial divide, while I put something like range as key of the melody as structural, you could imagine that you could have hte same interval invariant structure of a melody , perhaps Twinkle, Twinkle little star begginging on C2 noteated in bass cleff, but then imagine the the same "melody" being played two and a half octaves up on F#4, and transposed to minor and played quicker leading ot a phenomenologically similar experience, but not the same.
I taxonimze them early on, but again note that a model of this should be able withstand the multitude of patterns that exist. 

#### Make a Model of them 

Given all of these factors that then go into the melodic dictaiton process, the remainder of this chapter will detail previous reserach that has gone into each of these factors.
Talking about each one will provide rationale for why it should be further investigated if we are to better understand melodic dictation.
Beginning with *cognitive factors* two levels, then go on to talk about *musical features*.
After discussing both and their two subcompoents as I have taxonimzed them, offer a brief discussion on how it's bad to think about these as just latent abilities.
Instead talk about thinking about modeling melodic dictaiton, in terms of ACTUAL MODELING, as polymorphic conceptualization of aural skills. 
This is important because how we talk about and model things reflects or values and often it will get in the way of stuff. 


```{r}
# library(DiagrammeR)
# 
# grViz("
#      digraph boxes_and_circles {
# 
#   # a 'graph' statement
#   graph [overlap = true, fontsize = 10]
# 
#   # several 'node' statements
#   node [shape = box,
#         fontname = Helvetica]
#   Individual ; Musical ; Cognitive ; Environmental ; Structural ; Experimental 
# 
#   node [shape = box] // sets as circles
#   WMC; Gf; CowanList; Musical_Training; Aural_Training; 
#   Interval_Structure; Times_Played; Tempo; AuralSkills
# 
#   # several 'edge' statements
#   AuralSkills -> Individual
#   AuralSkills -> Musical
#   Individual -> Cognitive
#   Individual -> Environmental
#   Musical -> Structural
#   Musical -> Experimental
#   Cognitive -> WMC
#   Cognitive -> Gf
#   Cognitive -> CowanList
#   Environmental -> Musical_Training
#   Environmental -> Aural_Training
#   Structural -> Interval_Structure 
#   Experimental -> Times_Played
#   Experimental -> Tempo
# } 
#       
#       ")

```

## Individual Factors

### Cognitive

Research from the cognitive psychology literature suggests that individuals differ in their percetual and cognitive abilities in ways that are not easily influenced by short term-training (cite) and that these abilities, when investigated on a large scale are predictive of a wealth of human behavior from RICHIE CITATIONS.
If literature exists that suggests that cognitive abilites are sucessful predictors of things related to something like academic achievement, it worth investigating the extent that these abilities might play when modeling melodic dictation.
This is also important to understand because if we were to find out that something as simple as general fluid intelligence was a strong predictor in musical tasks that we are grading people on, it would be pretty unfair to do since we are then basiclly grading people on genetic factors beyond their control, as well as environmental factors shown to have some sort of effect on IQ (Richie paper again).
Recenlty there has been a surge of interest in this area (nancy rogers, LVH, utah guy, karinkski icmpc, form at SMT) probably due to the fact that educators are picking up on the fact that cognitive abilities are powerful predictors and need to be understood since they ineveitably will play a role in pedagogical settings. 

Before diving into a discussion regarding differences in cognitive ability, I should note that sometimes ideas regarding differnces in cognitive ability been hostily recieved (citation against people talking about IQ) and for good reasons.
Research in this area can and has been taken advantage to further dangerous ideologies (Bell Curve), but often arguments that assert meaningful differences in cognitiev abilites between groups are founed on statistical misunderstandings and have been debunked in other literature (measure of man).
With that cleared out of the way, it is very hard to mantain a scientific commitment to the theory of evolution (Darwin) and not expect variation in all aspects of human behavior, with cognition falling within that umbrella.

Attempting to measure aspects of cognition go back over a century.
Even before concepts of intelligence were posited by Charles Spearman and his conception of _g_ (Spearman, 1904), scientists were intersted in finding links between an individual's mental abilities and some sort of physical manifestation.
This area of research was pretty dark and kind of implicitly was all about validating preconceutalized ideas that people had on the superiority of peoples, with white dudes always comign out on top.
For example, THIS GUY WHO TRIED TO QUANTIFY GREATNESS
Also this guy who basically measured people's skull sizes.
But of course this stuff is not meaningful at all, especially when the dependent variable in this was so subjective and constrained by a culture where one ruling people (white dudes) had all the power.

I only mention this because this line of thinking was co-opted by the American herediterian school of IQ (page 187 in Gould), where people that were after the same sort of idea (superiority of white people) basically took ideas of Alfred Binet, one of the first people to begin to systematically investigate cognitive ability in children at request of the french governement so that children who were, what today we would call learning disabled, could be identified and given special attention.
Binet also took a lot of inspiration from Broca, WHO I TALK ABOUT ABOVE ON SKULL SIZE.

Bient was the initial developer of the idea of an intelligence quotient (divide mental age by chronological age then multiply by 100) and provided one of the first ways to attempt to measure something that was not capable of being manifested in the phsysical world. 
Around the same time have people like Cyrial Burt and Charles spearmean developing new theories of intelligence based on the reification factor analysis and calling it g that is based on solving problems without prior knowledge. 

sentence here about g and the postive manifold

Of course took this aside to talk about that basiclaly Binet and Spearman's ideologies about what can be measusred still represent two of the largest schools of thought on ways to meausre cognitive ability.
On one hand there idea that cognitive abilities are based upon a steady growth of incoming information that someone is able to manipulate once they retrieve from long term memory, the other hand is that in addition to that there is some sort of construct in the mind that differs between people that can singularly refelect their intelligence, often referred to as g. 

Basic assumption is that there is something in the brain here where differences will lead to different behaviors. 
Without detailing entire histories of this line of thought, Binet basically turned into an argument for general crystalized intelligence, or DEFINITINO HERE (citation).
The Spearman, Burt strain of thought evolved into the _g_ school, and recent reserach has suggested that the concept of _g_ basically is statistcally equnivlient to idea conceptualized as general fluid intelligence (cite that in POT).
Both of these constructs are powerful predictors on a large scale, but they don't explain the entire picture.

Another large area in the field of cognitve psychology is the area of working memory capacity.
As noted in Cowan 2005, what the term refers depends on the framework that is being used, but generally refers to the amount of information that can be acvtively held in concsionus representation, akin to short term memory, but with some important caveats discssed below. 
In additon to concepts of intelligence, be it Gf or Gc, the working memory capcity literature has done a lot of the heavy theoretical lifting, and after reviewing it we will have a much better idea of how once you decide about how you conceptualize it, then it's helpful. 

Given this brief background on cognitive ability, going to now dive deeper into both working memory capcity, as well as general fluid intelligence (avoid calling it _g_ for good reasons) and review literature where these have been discussed as they relate to research on music perception, thus being related to melodic dictation, a skill that you need to percieve music to be able to do? 

### Working Memory Capacity

As noted by Berz 1994, tasks of melodic dictation are basically tasks of working memory.

* [@berzWorkingMemoryMusic1995]

Quoting from him directly 

> Here is his quote

Clearly, would be worth understanding the concept at a deeper level since clealry they have done a lot of great work on the topic. 
Adoptiong chrnological take of the history of research the heavy hitters are 
* Attkinson and Shriff 
* Miller 1956 and why that is a bad idea
* Baddely and Hitch 
* Nelson Cowan + need for complex span

For reasons discussed on p 18 of cowan 2005 and page 42 , choose to adopot a Cowanian view where WMC is basically the window of attention.
Additinally it's worth noting initially that you can't directly apply these frameworks to memory for musical material because after reading page 109 in Cowan, important to note that all melodies appear in serial order. 
To make analogous task based on something like complex span tasks, would need to take certain set of notes and then always a finate setb be played back in arandom order (see chatper 3)

So while for my purposes, I will refer to it as listed on page 1 of Cowan 2005:

> [Working memory capacity] refers to the relativly small amount of information that one can hold in mind, attend to, or, technically speaking, maintain in a rapidly accesible state at one time. The term working is mean to indicate that meantal work requres use of such informaiton. (p.1])

But in the literature below I comment on which definitional framework is used if relevant to the reporting of it all.

#### Papers that suggest WMC plays a role

* [@nicholsScoreOneJazz2018]
* Halpern paper on conductors
* Sight reading paper 

Summerize 

### General Intelligence

As discussed above gf has a long history, some good some bad.
Thing is that it can be really predictive of many things and people def do try incoproate it into music research.

One of the big problems with this is establishing effects of causality looking at music.
Could be that factors outside of music play a role like persanal views of ability (Daniel paper), socio economic status, and personality.
And field is even big enough to have null results (include that catty comment of glenn schellenberg)

* Stuff on mozart effect 
* Whole chapter from Schellenberg
* Swaminithan papers

#### Papers that suggest GF plays a role

### Environmental 

### Long term memory and corpus with implicit

Standing in contrast to factors that individuals do not have a much control over such as the size of their working memory capapacity or factors related to their general fluid intelligence, most of the factors we believe contribute to someone's abililty to take melodic dictation have to deal with factors related to training and the envirionment.
In fact, one of the tacit assumptions of getting a music degree revolves around the implictly held belief that with delibrate and attentive practice, that an individual is able to move from novice to expertise in their chosen domain.
The idea that time invested results in beneficial returns is probably best exemplified by work produced by ANDERS ERICKSON 1993 that suggests that performance at more elite levels has to do with delibreate practice.
Below I review literature that supports this argument, since it's no doubt that someone has to engage in something to be good at it. 

### Musical Training 

It almost seems redundant to review literature in support of music practice leading to better results.

* List of those papers here

### Aural Training 

* Dictation has not been that well researched [@furbyEffectsPeerTutoring2016] 
* people try lots of things, not much evidence for peer tutoring [@furbyEffectsPeerTutoring2016]
* ISOLATION OF RHTYM AND MELODY
  - Banton 1995
  - Bland 1984
  - Root 1931
  - Wilson 1954
* LISTENING BEFORE WRITING
  - Banton 1995
* RECOGNIZING PATTERNS
  - Banton 1995
  - Bland 1984
  - Root 1931
* SINGING SILENTLY WHEN DICRTAING
  - [@klonoskiImprovingDictationAuralSkills2006]
  


### Sight Singing 

* [@fournierCognitiveStrategiesSightsinging2017a]  - catalogugig different strategizes used in sight signings
  - four main categories
  - 14 subcategories


### To Sort

* Harrison 1994
*  

## Musical Factors

Clealrly strutures also will play a role in this. 


* MEYER 1956
* HURON 2006
* [@margulisModelMelodicExpectation2005]

* Obviously not an exact match with perception CITE SCHENKER 

### Not first to model structure

* Long found that lenght, tonal structure, contour, and individual traits all contribute and also found that structure and tonalness (AS COMPUTED HOW) are good predictors [@longRelationshipsPitchMemory1977]
* Problem with long is that they eliminated people who werre bad singers for the example, this is at odds both with intutiion of representatino not being perfect mapping to singing, and has been DEMONSTRATED BY THESE PAPERS BY PETER PFORDRESHER.



### Early papers of Ortmann

* [@ortmannTonalDeterminantsMelodic1933]

### Papers from Mid 20th Century

( got these from paney 2016)

* EFFECT OF TEMPO HOFSTETTTER 1981
* TONALITY DOWLING 1978
* TONALITY LONG 1977 (already mentioned somehere else)
* OURA AND HATANO 1988
* TONALITY [@pembrookInterferenceTranscriptionProcess1986]
* SIZE OF INTERVALS [@ortmannTonalDeterminantsMelodic1933]
* CONJUNCT VS DISJUNCT MVT ORTMAN 1933 PEMBROOK
* length of the melody (Gephardt, 1978; Long, 1977;
Pembrook, 1986), 
* number of presentations of the melody (Hofstetter, 1981; Pembrook, 1986),
* context of the presentations (Schellenberg, 1985)
* participants’ musical experience (Long, 1977; Oura & Hatano, 1988; Schellenberg, 1985; Taylor & Pembrook, 1983), 
* Familiarity with the style of music (Schellenberg, 1985).
* [@taylorStrategiesMemoryShort1983] Extensin of Ortmann and looked at more musical skills, shows ways to suggest scoring simple melodies


* [@ouraConstructingRepresentationMelody1991a] - sampel of 8 but pretty much suggests that there is quick pattern matching that happens as it is drawn from LTM, 
* [@paneyEffectDirectingAttention2016] - if you direct attention, people do better at melodic dictation. said the next four were the only things looking at dictation since 2000
* Gillespie 2001 - HOW DO PEOPLE SCORE MELODIES
* Norris 2003 achievement and melodic dictation and sight singing CLEARLY A RELATIONSHIP
* [@pembrookSendHelpAural1990] - 
* [@paneyTeachingMelodicDictation2014] interviewed HS teachers on how they teach it for APi

* [@pembrookInterferenceTranscriptionProcess1986] - discussin here wher used tonality, melodic length, and motion, interesting also restricted melodies to ones you can sing. Found length, tonality and motion to be signficant at 13 3 1 variance. Though seems like with this there is a lot of chance for type I error and IS THERE EVEN ENOUGH INFO HERE IN THE PAPER TO RECREATE IT ALL. Also claims that people can hear about 10--16 notes, tho DJB would add this is obviously dependent on what i refer to as musical experimental factors and would not make sense to carry this logic forwad without more constraints. 

### Buonviri Papers

* [@buonviriEffectsMusicNotation2015; @buonviriEffectsPreparatorySinging2015; @buonviriEffectsTwoListening2017; @buonviriExplorationUndergraduateMusic2014; @buonviriMelodicDictationInstruction2015; @paneyTeachingMelodicDictation2014]

### Caveat about dilberate practice and talent

Also should mention here that clealrly not a perfect one dimensional model where effort equals results.
Simple thought expeiment that hard work does not always equal sucess in that there are sucssfull people who have not worked hard and very hard workers who do not experience sucess in what they do.
Additionally people need to keep up the skills they have, insert hilarious quote here from potter not believing that people didnt keep up their melodic dictaiton skills and show that they are compartmentalized [@potterIdentifyingSucessfulDictation1990]
This of course does not nullify any findings on delibreate practice, but goes to show that the whole thing is kind of complicated. 


### FANTASTIC papers and findings

### Brief discussion on Individual and Envirnoment Interactions


## Modeling and Polymorphism of Ability (End Chapter)
### Draw from MMD ICMCP on problems with LV model 
### Thought experiments on why musicianship is bad concept in general
### Polymophic, component process makes you think about things in models
## Conclusions
### Clearly we have factors that are thought to contribute, need to investigate them in full with each chapter
### Not before first looking at why we are doing it in the first place (--transition to Chapter 2)

<!--chapter:end:01-theoretical-bkgrd-rationale.Rmd-->

# History of Aural Skills 

## Thesis: Show that aural skills always has practical end, efficacy of representation of musical pitch
### for i in star aural people do
### Who
### Where
### When
### What 
### How (approach and goals)
### Why
### Guido d'Arezzo
### Walerant (via Calvisius)
### Banchieri 
### Cerratto
### Penna
### Zarlino 
## Quotes from Schumann 
## Carl Seashore thinking in music 
## Points from Karpinski on pedagogy
## Points from Royal Paper on pedagogy
## Solmization System
## Really this is all question of efficacy of mental representation of musical pitch

<!--chapter:end:02-history-current-aural.Rmd-->

# Individual Differences

## Why care about cognitive abilities
### General intelligence and WMC 
### Defining of terms
## Have established that cognitive abilities contribute to musical task (for journal article langauge repeat)
### General Fluid Intelligence, WMC, Training as uni of polymorphic
## Remind the nature of a musical dictation type task (hear, loop, executive decision)  
### This is WMC task, gf has problems (Although high level link with gf, problematic, WMC models at level of process of md)
#### Berz 1994 noticed it first
#### Williamson Baddely Hitch suggest maybe musical loop
#### Even Cowan labs wonder how different (Li Cowan Saults )
## WMC has been misused in music education, theory, pedagogy, aural literature and deserves attention
### Problems with chunking 
#### Mistake with Miller 1956, he did not mean 7 items
#### Broadbent 1956 more of why its more like 3-4
### Problems with using capacity limit literature
#### See Cowan 2005 page 80
#### Musical order is always serial effects
### Should be using Cowan model because of these things (zooming) or discuss within Baddely Hitch/Atkinson Shriff
### One Note does not mean one unit in memory!
### Confounded by corpus distributions
### Lack of understanding (all aural skills are those that engage WMC, LVH says many students have WMC deficits, "increase memory")
### Point I am making is that if you're going to do it, do it well. 
## Know WMC plays a role, sense, pertain, execute, should be able to pick up in experiment close to MD
## Gold-MSI melodic Memory and beat perception test
### What is gold MSI 
### What are issues I want to talk about with psychometrics
### Describe test in detail and WHY it's what we're after here
#### not exactly mmd, but most people would say similar skill sets
#### also before getting dirty,need experimental desing with less response options (Cowan, Saults, Elliott, Moreano 2002)
## IF we accept these DVs, THEN we should be able to predict them with self reports and measures of WMC and gf
## Do this with hierarchical LVM ala Elliott paper 
### Versions of this paper at ICMPC
### Exploratory in that tried a few different models (high type I error but whatever)
## Overview of Experiment (cross sectional design)
### Participants
### Materials
### Procedure
### Results
#### Descriptive, Correlational
#### Modeling
### Discussion
#### Review of the Goals
#### What were best model fits
#### Clear effect of WMC
#### What if we are just measuring WMC? 
#### Obvs need this for futre studies
#### Need to use something to go above and beyond baseline (--transition to corpus as memory and n-gram)
#### Future verbal theoretical and computational models should involve capacity measures (limits)
 

<!--chapter:end:03-individual-parameters.Rmd-->

# Computation Chapter

## Humans like patterns and are very good at picking them up
### We learn things implicitly
### We can represent that implicit knowledge with a corpus 
## Pre-Musical Corpora
### Information Theory
### Computational Linguistics as front runner
## Musical Corpora
### History of Musical Corpora 
#### Fun old computational music papers 
#### Corpora that are often used
#### Static vs Dynamic models of feature abstraction (daniel slides?)
### FANTASTIC 
#### static 
#### ML approach gets it right
#### simple to understand
#### Can abstract features be percieved? 
###### Note density
###### Contour variation
###### Tonalness
###### weird computational measures
### IDyOM as representation of musical materials 
#### n-gram models
#### mirrors human behavior
###### melody
###### harmony
## So What?
#### Other research (Chapt 3) suggest need to move beyond cognitive measures
#### Can operationalize item level items contextually with a corpus 
#### IF features are real, they should effect dictation (Chater 6)
#### Not only important for one off, but then would be incorporated into computational learning models (Chapter 6)
#### We need new materials 

<!--chapter:end:04-musical-parameters.Rmd-->

# Hello, Corpus

## Brief review of Chapter 4 on corpus (Language to reflect journal submission)
### Corpus outside of music
### Corpus in Music
### The point is that it implicitly represents humand knowledge
### IDyOM 1
### IDyOM 2
### IDyOM 3
### Huron suggestions that starts of melodies relate to mental rotaiton 
### Other Huron claims
## Note problem with using corpus is making corpus
### Many are used on Essen
### Brinkman says Essen Sucks
### If going to make generlizable claims, need to always have new data 
## Solem duty to encode and report on corpus
### Justin London Article on what makes it into a corpsu
### Though I just encoded the whole thing because in my heart of hearts I'm a Bayesian
## The Corpus
### History of Sight Singign books
### Assumed to be where long term store comes from (adumbrate computational model)
### Lots of melodies in ascending order of difficulty, grouped appropriately though? Utah guy
### Why I encoded it in XML  
### Is it legal?
## Descriptive Stats of Corpus
### Why?
#### For pedagogical purposes
#### For experimental purposes
#### For computational idexing (get me melody with x tonal score)
#### Could serve as representation of implicitly learned expectations for future modeling
### Feature Level
#### What features are normally distributed
#### Correlated feature problem
#### big ~facet wrap of the whole thing
#### Could do dimensonality reduction (Baker, Harrison, others) but then loose understanding
### n-gram
#### Big solfege n-gram table
#### Dependent on representation (notes, solfege, mint)
#### Shiny app of n-gram heatmap with Peter
#### Idea would be that hotter n-grams lend them selves to better chunking (but need better word than chunking)


<!--chapter:end:05-corpus.Rmd-->

# Experiments

## Rationale 
### Have done all this and have not actually talked about dictation yet 
### Clearly many factors contribte to this whole thing and need to be taken into a model 
### Dictation is basically a within subjects design Experiment
#### Get very ecological and dirty and run it 
### Factors
#### Cognitive
##### WMC
##### GF
#### Training
##### Goldsmiths MSI 
#### Musical 
##### FANTASTIC
##### IDyOM
#### Investigate melodies with this context and set scoring 
#### Mirror design to see if effects of melody are there

## Experiments
### Experiment I
#### Participants
#### Procedure
#### Materials
#### Scoring 
#### Results
#### Modeling
#### Discussion 
### Experiment II
#### Participants (New)
#### Procedure (Same)
#### Materials (Swapped but controlled)
#### Scoring (Same)
#### Results
#### Modeling (same)
### General Discussion 
#### What happened
#### Assumption of all of this is that many things are happening linearly in combination with each other
#### Additionally the mixed effects framework works better with more data? 
#### Also how we score it is going to mess wiht the DVs
### Really what is needed is Computational Model 

## Computational Cognitive Model Model (If time permits) [Whole article in itself]
### Why?
##### Better than verbal models
##### Sometimes even mathematically infesable proposed theory
##### Beyond Karpinski in that it doesn't just schematize, says exactly when each thing is happening when
##### Lends itself to better discussions that don't just rely on personal anecdotes
##### Can tweak the parameters 
##### Can collect different types of data (corpus or experimental) and use the model
##### This model suggests that atomism approach is actual just subprocess of larger pattern 
#### Theoretical Justification
##### Marries literature on LTM and prior knowledge, information theory, WMC, computation, representation
##### Also can be implemented in computer
##### represntation of rhythm too?
##### inspired by people like margulis 2005, albrecht and shanahan key finding, want something to contribute
##### Really Made me think
#### The Model (note many parameters can be changed in R package)
#### Prior
###### Corpus of music represented in form of n-grams
###### IDyOM extracts all possible n-gram permutations as learned corpus
##### Music notation fed into processing window where incoming n-gram is matched based on WMC window OR IT maximum 
###### Information builds until approaches critical threhold 
###### Upon maximum, model puts n-gram into focus of attention (Cowan 1988) and note why this is better than Baddely Hitch
###### Recursive transcribe function looks for LTM matches 
####### Option 1: Pattern Matched and Pattern Transcribed, success?
####### Option 2: Pattern not matched in full, truncated and use match option again (should be higher probability of match with corpus)
####### Option 3: Pattern not matched downsize again until at interval level and relying on 2-gram (atomism)
####### On sucess of option, reopen gate at nearest long implicit n-gram LTM Match (start or end problem)
###### Put time contraints on search features 
###### Transcribe process resets with trace image of melody after each dictation 
###### Transcribe process ends when all notes accounted for 
#### Model Output
##### Based on leanrning, times needed to hear it
##### Completion percentage
##### Rank order of easier to transcribe parts based on learning
#### Model Compared to Data
##### With Experimental Data 
### Future Suggestions for Aural Skills Pedagoges and Research
#### Use model as teaching stepping off point
#### Should move towards LTM pattern matching
#### Reason that people learn how to sight sing is to INCREASE the learning of the implict corpus
#### Circular process here
#### Is this what it means to then think IN music
#### Really it's to just know the patterns maybe like model where Justin London suggests we get to know patterns and expect themn
#### Would also make sense in terms of Leonard Meyer 1956
#### Use WMC in music theory, cognition, education studies
 

<!--chapter:end:06-experiments.Rmd-->

---
output:
  html_document: default
  pdf_document: default
---
# Reference Log 

## To Incorporate

* [@margulisModelMelodicExpectation2005] -- Margulis Model 
* [@nicholsScoreOneJazz2018] -- Specialty jazz background helps in tasks, WMC
* [@NASM201718HandbookPdf2018] -- Fix intext
* [@schumann1860musikalische] -- Quote about why people should do ear training
* [@smith1934solfege] -- Quote from K2001 about why people should do ear training
* [@longRelationshipsPitchMemory1977] -- Musical Characteristics predict memory
* [@taylorStrategiesMemoryShort1983] -- Great citation that lots of things change memory, even structural! 
* [@tallaricoStudyThreePhase1974] -- Long boring talk on STM, LTM
* [@ouraConstructingRepresentationMelody1991a] -- Awful experimental design that says people use structual tones
* [@buonviriExplorationUndergraduateMusic2014] -- Call for experimental, suggestions as to what factors might contribute, use of deductive reasoning, qualitative
* [@buonviriEffectsPreparatorySinging2015] -- People need to focus right away, not establish, distractors
* [@buonviriEffectsMusicNotation2015] -- Showing people visual music does not help much.
* [@buonviriEffectsTwoListening2017] -- Listening helps with other things, no best strategy in terms of writing
* [@buonviriMelodicDictationInstruction2015] -- Literature to say people are bad at teaching melodic dictation and we don't know a lot about it, also interesting stuff about what solfege systems people use
* [@davidbutlerWhyGulfMusic1997a] -- Call for music educators to do aural skills research, notes problem with aural skills pedagogy in lack of direction, also nice Nicholas Cook quotes on point of theory
* [@furbyEffectsPeerTutoring2016] -- music ed study with weird stats, has references to follow up on with advantages of pitch systems and people who reccomend things for sight singing
* [@pembrookInterferenceTranscriptionProcess1986] -- Effects of melodies, also how people do it. Interesting that they too effect of melodies, but talka bout things in terms of notes and not in terms of information content. Thought ot have an experiment where the n-grams that are more common are easier to write down. Lots of good charts too. 
* [@paneyEffectDirectingAttention2016] -- It's not good if you tell people what to do when they are dictating, article has a lot of good review for dictation materials to add to the 'toRead' folder.
* [@fournierCognitiveStrategiesSightsinging2017a] -- Good references that people are awful at Aural Skills, Also suggestions that people are not that great at transfer, and some stuff to suggest academic abililty is intertwined in all of this. Good reference for when starting to talk about untangling the mess that is aural skills. 
* [@berzWorkingMemoryMusic 1995] -- Add on a new module to the WMC model of baddel with music, presents some evidence for why this theoretically should be included, but actually takes examples of dictation. A lot of this article felt like things that i was reinventing...not  good.
* [@atkinsonSomeThoughtsOnTrying] -- Proof some other people are starting to think in terms of pedagogical schemas
* [@klonoskiPerceptualLearningHierarchy2000] -- Music cognition needs to talk to aural skills more, also need to unbind theory routine with aural skills and think of things more as in a perceptual learning hierarchy 
* [@klonoskiImprovingDictationAuralSkills2006] -- great quotes that when people get something wrong with aural skills, what does that even mean, lack of transfer effects, article ends with ways to get better at things
* [@pembrookSendHelpAural1990] -- Survey of what people in the late 1980s were doing in terms of aural skills pedagogy
* [@karpinskiModelMelodicPerception1990] -- addresses why Gary Karpinski thinks we should teach melodic dictation
* [@potterIdentifyingSucessfulDictation1990] -- dictation teacher surprised that people don't keep up their dictaiton skills quote

## Chapter 3

* [@cowanWorkingMemoryCapacity2005] -- This book will probably serve as cornerstone of chapter in terms of creating relevant literature in addition to EE course readings on WMC. Provides history of WMC models and notes how attention based model as opposed to Baddely loop might actually be better theoretical model for talking about fact that WMC could just be something related to attention if not that. Provides extensive listing on problems with chunking that are all relevant to music, but then also supports it. Shows that Miller 1956 is a generally bad citation, own author even says that in Miller 1989 (check and add) and says limit is probably about 4 (use Cowan 2001 for ctation find that). Lots of good ideas like how music is always serial recall, examples of how to model the process, great discussions on zooming out and categorical nature of music within span of WMC ideas.

* [@ockelfordMusicModuleWorking2007] -- uses case of savant to argue bits of Berz WM Music Model


<!--chapter:end:061-reflog.Rmd-->

`r if (knitr:::is_html_output()) '
# References {-}
'`

<!--chapter:end:07-references.Rmd-->

