---
title: "Rough-Outline"
author: "David John Baker"
date: "August 27, 2018"
output: html_document
---

## Chapter 1

* Theoretical Background Rationale for Computational Musicology and cognitive psychology
  + This is important for XYZ for reason to study
  + What is melodic dictation? 
    + Describe process
    + Karpinski schematic of it (as verbal model, problems)
      + Verbal model, has problems, OK for pedagogy
      + Verbal model, no individual differnces tho literture to suggest
      + Computational model to be introduced
    + Clearly this is psychological problem with different item level difficulty   
      + Individual Factors to contribute 
      + Musical factors to contribute
      + Make a Model of them 
  + Cognitive Factors (MT and it selection bias)
    + Working Memory Capacity
      + Papers that suggest WMC plays a role
    + General Fluid Intelligence
      + Papers that suggest GF plays a role
    + Long term memory and corpus with implicit
    + Musical Training 
    + Aural Training 
  + Musical Factors
    + Not first to model structure
    + Early papers of Ortmann
    + Papers from 1980s 
    + Buonviri Papers
    + FANTASTIC papers and findings
  + Modeling and Polymorphism of Ability (End Chapter)
    + Draw from MMD ICMCP on problems with LV model 
    + Thought experiments on why musicianship is bad concept in general
    + Polymophic, component process makes you think about things in models
  + Conclusions
    + Clearly we have factors that are thought to contribute, need to investigate them in full with each chapter
    + Not before first looking at why we are doing it in the first place (--transition to Chapter 2)

## Chapter 2

* Long history in Western Music of Aural Skills
  + Thesis: Show that aural skills always has practical end, efficacy of representation of musical pitch
      + for i in star aural people do
      + Who
      + Where
      + When
      + What 
      + How (approach and goals)
      + Why
    + Guido d'Arezzo
    + Walerant (via Calvisius)
    + Banchieri 
    + Cerratto
    + Penna
    + Zarlino 
  + Quotes from Schumann 
  + Carl Seashore thinking in music 
  + Points from Karpinski on pedagogy
  + Points from Royal Paper on pedagogy
  + Solmization System
  + Really this is all question of efficacy of mental representation of musical pitch

## Chapter 3

* Individual Differences (ICMPC First draft)
  + Why care about cognitive abilities
    + General intelligence and WMC 
    + Defining of terms
  + Have established that cognitive abilities contribute to musical task (for journal article langauge repeat)
    + General Fluid Intelligence, WMC, Training as uni of polymorphic
  + Remind the nature of a musical dictation type task (hear, loop, executive decision)  
  + This is WMC task, gf has problems (Although high level link with gf, problematic, WMC models at level of process of md)
    + Berz 1994 noticed it first
    + Williamson Baddely Hitch suggest maybe musical loop
    + Even Cowan labs wonder how different (Li Cowan Saults )
  + WMC has been misused in music education, theory, pedagogy, aural literature and deserves attention
    + Problems with chunking 
      + Mistake with Miller 1956, he did not mean 7 items
      + Broadbent 1956 more of why its more like 3-4
    + Problems with using capacity limit literature
      + See Cowan 2005 page 80
      + Musical order is always serial effects
    + Should be using Cowan model because of these things (zooming) or discuss within Baddely Hitch/Atkinson Shriff
    + One Note does not mean one unit in memory!
    + Confounded by corpus distributions
    + Lack of understanding (all aural skills are those that engage WMC, LVH says many students have WMC deficits, "increase memory")
    + Point I am making is that if you're going to do it, do it well. 
  + Know WMC plays a role, sense, pertain, execute, should be able to pick up in experiment close to MD
  + Gold-MSI melodic Memory and beat perception test
    + What is gold MSI 
    + What are issues I want to talk about with psychometrics
    + Describe test in detail and WHY it's what we're after here
      + not exactly mmd, but most people would say similar skill sets
      + also before getting dirty,need experimental desing with less response options (Cowan, Saults, Elliott, Moreano 2002)
  + IF we accept these DVs, THEN we should be able to predict them with self reports and measures of WMC and gf
  + Do this with hierarchical LVM ala Elliott paper 
    + Versions of this paper at ICMPC
    + Exploratory in that tried a few different models (high type I error but whatever)
    
* Experiment
  + Overview of Experiment (cross sectional design)
  + Participants
  + Materials
  + Procedure
  + Results
    + Descriptive, Correlational
    + Modeling
  + Discussion
    + Review of the Goals
    + What were best model fits
    + Clear effect of WMC
    + What if we are just measuring WMC? 
    + Obvs need this for futre studies
    + Need to use something to go above and beyond baseline (--transition to corpus as memory and n-gram)
    + Future verbal theoretical and computational models should involve capacity measures (limits)
  
## Chapter 4

* Computation Chapter
  + Humans like patterns and are very good at picking them up
    + We learn things implicitly
    + We can represent that implicit knowledge with a corpus 
  + Pre-Musical Corpora
    + Information Theory
    + Computational Linguistics as front runner
  + Musical Corpora
    + History of Musical Corpora 
      + Fun old computational music papers 
      + Corpora that are often used
      + Static vs Dynamic models of feature abstraction (daniel slides?)
    + FANTASTIC 
      + static 
      + ML approach gets it right
      + simple to understand
      + Can abstract features be percieved? 
        + Note density
        + Contour variation
        + Tonalness
        + weird computational measures
    + IDyOM as representation of musical materials 
      + n-gram models
      + mirrors human behavior
        + melody
        + harmony
    + So What?
      + Other research (Chapt 3) suggest need to move beyond cognitive measures
      + Can operationalize item level items contextually with a corpus 
      + IF features are real, they should effect dictation (Chater 6)
      + Not only important for one off, but then would be incorporated into computational learning models (Chapter 6)
      + We need new materials 

## Chapter 5

* Hello, corpus
  + Brief review of Chapter 4 on corpus (Language to reflect journal submission)
    + Corpus outside of music
    + Corpus in Music
    + The point is that it implicitly represents humand knowledge
      + IDyOM 1
      + IDyOM 2
      + IDyOM 3
      + Huron suggestions that starts of melodies relate to mental rotaiton 
      + Other Huron claims
  + Note problem with using corpus is making corpus
    + Many are used on Essen
    + Brinkman says Essen Sucks
    + If going to make generlizable claims, need to always have new data 
  + Solem duty to encode and report on corpus
    + Justin London Article on what makes it into a corpsu
    + Though I just encoded the whole thing because in my heart of hearts I'm a Bayesian
  + The Corpus
    + History of Sight Singign books
    + Assumed to be where long term store comes from (adumbrate computational model)
    + Lots of melodies in ascending order of difficulty, grouped appropriately though? Utah guy
    + Why I encoded it in XML  
    + Is it legal?
  + Descriptive Stats of Corpus
    + Why?
      + For pedagogical purposes
      + For experimental purposes
      + For computational idexing (get me melody with x tonal score)
      + Could serve as representation of implicitly learned expectations for future modeling
    + Feature Level
      + What features are normally distributed
      + Correlated feature problem
        + big ~facet wrap of the whole thing
        + Could do dimensonality reduction (Baker, Harrison, others) but then loose understanding
    + n-gram
      + Big solfege n-gram table
      + Dependent on representation (notes, solfege, mint)
      + Shiny app of n-gram heatmap with Peter
      + Idea would be that hotter n-grams lend them selves to better chunking (but need better word than chunking)
  
## Chapter 6

* Rationale (ICMPC Paper on MMD)
  + Have done all this and have not actually talked about dictation yet 
  + Clearly many factors contribte to this whole thing and need to be taken into a model 
  + Dictation is basically a within subjects design Experiment
    + Get very ecological and dirty and run it 
  + Factors
    + Cognitive
      + WMC
      + GF
    + Training
      + Goldsmiths MSI 
    + Musical 
      + FANTASTIC
      + IDyOM
  + Investigate melodies with this context and set scoring 
  + Mirror design to see if effects of melody are there

* Experiments
  + Experiment I
    + Participants
    + Procedure
    + Materials
    + Scoring 
    + Results
      + Modeling
      + Discussion 
  + Experiment II
    + Participants (New)
    + Procedure (Same)
    + Materials (Swapped but controlled)
    + Scoring (Same)
    + Results
      + Modeling (same)
  + General Discussion 
    + What happened
    + Assumption of all of this is that many things are happening linearly in combination with each other
    + Additionally the mixed effects framework works better with more data? 
    + Also how we score it is going to mess wiht the DVs
    + Really what is needed is Computational Model 

* Computational Cognitive Model Model (If time permits) [Whole article in itself]
  + Why?
    + Better than verbal models
    + Sometimes even mathematically infesable proposed theory
    + Beyond Karpinski in that it doesn't just schematize, says exactly when each thing is happening when
    + Lends itself to better discussions that don't just rely on personal anecdotes
    + Can tweak the parameters 
    + Can collect different types of data (corpus or experimental) and use the model
    + This model suggests that atomism approach is actual just subprocess of larger pattern 
  + Theoretical Justification
    + Marries literature on LTM and prior knowledge, information theory, WMC, computation, representation
    + Also can be implemented in computer
    + represntation of rhythm too?
    + inspired by people like margulis 2005, albrecht and shanahan key finding, want something to contribute
    + Really Made me think
  + The Model (note many parameters can be changed in R package)
    + Prior
      + Corpus of music represented in form of n-grams
      + IDyOM extracts all possible n-gram permutations as learned corpus
    + Music notation fed into processing window where incoming n-gram is matched based on WMC window OR IT maximum 
      + Information builds until approaches critical threhold 
      + Upon maximum, model puts n-gram into focus of attention (Cowan 1988) and note why this is better than Baddely Hitch
      + Recursive transcribe function looks for LTM matches 
        + Option 1: Pattern Matched and Pattern Transcribed, success?
        + Option 2: Pattern not matched in full, truncated and use match option again (should be higher probability of match with corpus)
        + Option 3: Pattern not matched downsize again until at interval level and relying on 2-gram (atomism)
        + On sucess of option, reopen gate at nearest long implicit n-gram LTM Match (start or end problem)
      + Put time contraints on search features 
      + Transcribe process resets with trace image of melody after each dictation 
      + Transcribe process ends when all notes accounted for 
    + Model Output
      + Based on leanrning, times needed to hear it
      + Completion percentage
      + Rank order of easier to transcribe parts based on learning
    + Model Compared to Data
      + With Experimental Data 
  + Future Suggestions for Aural Skills Pedagoges and Research
    + Use model as teaching stepping off point
    + Should move towards LTM pattern matching
    + Reason that people learn how to sight sing is to INCREASE the learning of the implict corpus
    + Circular process here
    + Is this what it means to then think IN music
    + Really it's to just know the patterns maybe like model where Justin London suggests we get to know patterns and expect themn
    + Would also make sense in terms of Leonard Meyer 1956
    + Use WMC in music theory, cognition, education studies
    